### ISSUE TITLE
Npcap:  arp packet sent to myself cannot be responsed

### ISSUE THREAD

**Issue by ZacharyJia** [nmap/npcap#116]
Hello there, 
    I am using npcap for sending raw ethernet packets, but I've found there are some problems when I send an ARP response to myself.  I ping a specific IP address in my computer and my computer send a broadcast arp request. And then I construct a fake arp response packet from my computer and send it to myself. I can see from wireshark that the packet has been sent but my computer seems not receiving that packet and are still sending arp requests. I have tried to send arp request from another computer and reply arp response from my computer, and it works. I do the same thing with winpcap and it works too.
    Is this a bug or a feature that I cannot send packet to myself?  Are there any solution?
    My npcap version is 0.99-r7 and my os is win10 build 10.0.17134.320
    Thanks a lot.

**Comment by trivalik** [comment]
What I can say is, that this change the unit test TransmitQueueToLiveTest of Pcap.Net let fails, independent of set value of PacketSetLoopbackBehavior.
`PacketSetLoopbackBehavior(AdapterObject, 1);` leads to that no packets are received, sent by pcap_sendqueue_transmit.
PacketSetLoopbackBehavior(AdapterObject, 0); leads to that duplicate packets are received, sent by pcap_sendqueue_transmit.

**Comment by trivalik** [comment]
What I can say is, that the above commit 07c274ac9783752d2aa2ee3497aceccf38fb51e9 breaks the unit test TransmitQueueToLiveTest of Pcap.Net, independent of set value of PacketSetLoopbackBehavior.
`PacketSetLoopbackBehavior(AdapterObject, 1);` leads to that no packets are received, sent by pcap_sendqueue_transmit.
`PacketSetLoopbackBehavior(AdapterObject, 0);` leads to that duplicate packets are received, sent by pcap_sendqueue_transmit.

Test works with 0.998.

Hint: you have to remove `TestTransmitQueueToLive(0, 100, 0.5, false);` of the test! because of another npcap bug with 0 packets
