### ISSUE TITLE
Npcap Error opening adapter when running through Wireshark in administrator mode

### ISSUE THREAD

**Issue by wbobroff** [nmap/npcap#129]
Running Wireshark in administrator mode, capture image produces the following error message:
The capture session could not be initiated on interface '\Device\NPF_Loopback' (Error opening adapter: The system cannot find the path specified.  (3)).

The only interface listed on Wireshark is the adapter for loopback capture.
 
[DiagReport-20191019-015417.txt](https://github.com/nmap/nmap/files/3744584/DiagReport-20191019-015417.txt)

**Comment by dmiller-nmap** [comment]
This error is specific to Npcap 0.9983 to 0.9987, when the "Adapter for loopback capture" was listed even if loopback support was not available due to some internal  driver problem or if the driver was not started. For Npcap 0.9988 and later, the adapter will not be listed if it cannot be opened with the driver.
