### ISSUE TITLE
Show Label Name of Network device on Windows is possible? [npcap]

### ISSUE THREAD

**Issue by Zilog80c** [nmap/npcap#145]
Hi, 
  i have try on windows 10 and windows 7. 
When write a list of network device, don't appear in the list, the label name on windows , for expample:
PCIe GBE Family Controller  i label "Lan"
Intel Ac Wifi Controller i label "WiFi".

when list a network device 
\Device\NPF_{xxxxxxxx....xxxxx} (Realtek PCIe GBE Family Controller)
the label "LAN" are not present;
\Device\NPF_{xxxxxxx...xxxxxxx} (Microsoft)
the label "WiFI" is not present.

Thanks for help.

The Code for test are:

#include <stdio.h>
#include <stdlib.h>
#include <pcap/pcap.h>

int	i,inum;
char errbuf[32768];
pcap_t *net_pcap;
pcap_if_t *alldevs;
pcap_if_t *d;

int main(int argc, char **argv)
{
      if(pcap_findalldevs(&alldevs, errbuf) == -1)
				{
					fprintf(stderr,"Error in pcap_findalldevs: %s\n", errbuf);
					exit(1);
				}	
     	/* Print the list */
   		for(d=alldevs; d; d=d->next)
					{
						printf("%d. %s", ++i, d->name);
						if (d->description)
								printf(" (%s)\n", d->description);
						else
								printf(" (No description available)\n");
					}	
		 if(i==0)
						{
									printf("\nNo interfaces found! Make sure Npcap is installed.\n");
									return -1;
						}	
		printf("Enter the interface number (1-%d):",i);
		scanf("%d", &inum);
	  pcap_freealldevs(alldevs);
		exit (0);
}

**Comment by fyodor** [comment]
Thanks for report.  Would you please try with Npcap version 0.9991?  If you are still experiencing the problem with that version, please comment and then I'll reopen the issue.

**Comment by Zilog80c** [comment]
...... problem with that version, please comment and then I'll reopen the issue.
Hi fydor,
 Ok. Now show the name!

Very Very Thanks for help!

**Comment by massoudasadi** [comment]
problem exist in version 0.9994 & 0.9991 (windows 10 version 2004) @fyodor

**Comment by fyodor** [comment]
@massoudasadi  - are you sure it is the same problem?  How about trying Npcap version 0.9995 and, if you are still encountering a problem, please file a new issue with full details.  It might be something different than this one since the original reporter of this says it was resolved.  Thanks!

**Comment by guyharris** [comment]
What do you mean by the "label"?

If I open Control Panel on my Windows 10 (virtual) machine, click on "Network and Internet", and click on "View network status and tasks", it shows a network device named "Ethernet0".  If I plug in a USB Wi-Fi adapter, it shows up as "Wi-Fi 2".  Is "Ethernet0" the label of the Ethernet device, and is "Wi-Fi 2" the label of the Wi-Fi adapter?

**Comment by massoudasadi** [comment]
@fyodor same result in 0.9995
![2020-07-17](https://user-images.githubusercontent.com/11457976/87714203-abe85600-c7c0-11ea-8296-23795bef6f1f.png)

**Comment by guyharris** [comment]
If you're referring to the names such as "Ethernet", "Ethernet 2", "WI-FI", "vEthernet (WSL)", etc., those are the "friendly names" of the adapters.

It would be possible to supply them, but it would require either a change to the way the internal `PacketGetAdapterNames()` routine works, causing it to return "friendly names" rather than "descriptions", or a change to the way that the internal `pcap_platform_finddevs()` in pcap-npf.c works.

In addition, with the current libpcap APIs, it would also mean that the "descriptions", such as "Realtek PCIe GbE Family Controller", "Hyper-V Virtual Ethernet Adapter", "TAP Windows Adapter V9", etc. *not* be shown, as libpcap's `pcap_findalldevs()` returns two strings - a name (which is what you use to open the device, so it's not a descriptive name, in Npcap it's a path that includes the GUID for the adapter) and a description string, which could either be the "friendly name" or the "description", but not both.

**Comment by massoudasadi** [comment]
@guyharris thanks for your help but it's strange they don't provide friendly name of adaptors.
can i get interface name from ipconfig output and somehow compare it with npcap interface description to map them and get GUID of adaptor ?

**Comment by guyharris** [comment]
> it's strange they don't provide friendly name of adaptors.

Who are "they"?

The code in libpcap and Npcap originated in code that ran on Windows 95, 98, Me, NT 3.x and NT 4.0, where there *were* no friendly names; when that code was written, it was literally *impossible* to provide the "friendly names", as there were no such things as "friendly names".

Some software that's using WinPcap or Npcap might *expect* the description to be the "description" rather than the "friendly name", so it's not clear what would break if the code were to be *changed* to return "friendly names" rather than "descriptions".

The *right* fix is to add new APIs that, instead of providing per-interface information in a fixed structure, provide it in a form similar to [a pcapng Interface Description Block](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii#rfc.section.4.2), with all the interface characteristics other than the link-layer header type provided as "options".  That would allow the "friendly name" to be supplied as the if_description option and the "description" supplied as the if_hardware option, and would also make it easier to provide other information not currently provided by `pcap_findalldevs()`, such as MAC addresses and link speeds.

> can i get interface name from ipconfig output and somehow compare it with npcap interface description to map them and get GUID of adaptor ?

What you might try is to open the device and then use the

    int pcap_oid_get_request(pcap_t *, bpf_u_int32, void *, size_t *)

routine in Npcap, with the [`OID_GEN_FRIENDLY_NAME` OID](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-friendly-name) to get the friendly name.

Unfortunately, that routine isn't documented, but here's a start at writing documentation for it:

The `pcap_oid_get_request()` routine fetches the value of an NDIS OID for an open capture device.

The first argument is the `pcap_t *` for the capture device.

The second argument is the OID to be used.

The third argument is a pointer to a buffer into which to fetch the value.

The fourth argument is a pointer to a `size_t` variable.  It should be initialized to the size of the buffer; it will be set to the number of bytes of data actually fetched.

The return value is 0 on success and a PCAP_ERROR_ value on failure.  If the error return is `PCAP_ERROR`, a call to `pcap_geterr()` will return a pointer to a string giving the details of the error.

**Comment by joshuafc** [comment]
I have download sdk from https://npcap.com/#download

https://npcap.com/dist/npcap-1.79.exe
https://npcap.com/dist/npcap-sdk-1.13.zip

There is no pcap_oid_get_request in C:\Windows\system32\wpcap.dll

![Uploading 企业微信截图_17151547405865.png…]()

![Uploading 企业微信截图_17151547462404.png…]()

![Uploading 企业微信截图_17151547746299.png…]()
