### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by dfaulks** [nmap/npcap#150]
After installing Wireshark-win64-3.0.0.exe (which apparently comes with Npcap) on my Windows 10/64-bit Lenovo ThinkPad T430, my wireless adapter began to cycle on and off continuously. The tech support guy tried everything including driver upgrade/reinstall with no help. Unistalled Npcap and it fixed the problem.

**Comment by fyodor** [comment]
Hi.  I'm sorry nobody has specifically addressed your issue since it was filed more than a year ago.  But we have made major improvements since then.  If you get a chance to try with Npcap version 0.9991, there is a good chance it will work for you.  And if not, please file a new bug with details and we can investigate.  Thanks!
