### ISSUE TITLE
NCAP 0.99-r7 failed to setup on Windows10 family edition

### ISSUE THREAD

**Issue by zhenh-zhai** [nmap/npcap#154]
Hello,
I have some trouble installing npcap on my windows 10.
Unknown error 0x8007007e
[install.log](https://github.com/nmap/nmap/files/2999262/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/2999263/NPFInstall.log)
![TIM图片20190323191919](https://user-images.githubusercontent.com/26357319/54865434-9451b680-4da0-11e9-9d54-2fba6b274549.png)

Please give me some help.
Thank you!

**Comment by fyodor** [comment]
Hi.  I'm sorry nobody has specifically addressed your issue since it was filed more than a year ago.  But we have made major improvements since then.  If you get a chance to try with Npcap version 0.9991, there is a good chance it will work for you.  And if not, please file a new bug with details and we can investigate.  Thanks!
