### ISSUE TITLE
Bug Report - Service fails to install

### ISSUE THREAD

**Issue by mattsmith221** [nmap/npcap#155]
Hello! Currently trying to install NPCap for win10. Getting error that the service cannot be created. It seems I'm getting an access permission error, but I'm not sure how to resolve. Could you review the attached logs and provide feedback?

[install.log](https://github.com/nmap/nmap/files/2978914/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/2978915/NPFInstall.log)
[DiagReport-20190318-111820.txt](https://github.com/nmap/nmap/files/2978916/DiagReport-20190318-111820.txt)

**Comment by fyodor** [comment]
Hi.  I'm sorry nobody has specifically addressed your issue since it was filed more than a year ago.  But we have made major improvements since then.  If you get a chance to try with Npcap version 0.9991, there is a good chance it will work for you.  And if not, please file a new bug with details and we can investigate.  Thanks!
