### ISSUE TITLE
npcap 0.99-r9 interferes with Dell Connection Manager software

### ISSUE THREAD

**Issue by epaul137** [nmap/npcap#156]
When npcap is installed, Dell Connection Manager cannot detect a wired connection properly upon startup. When the wired connection fails, the wireless nic is not turned off and the icon in the system tray shows no wireless connection even though the ethernet port on the back of the dock shows a link and the switch port also shows a valid link. If you uninstall npcap, the wired connection is immediately detected and the wireless nic is turned off.

**Comment by fyodor** [comment]
Hi.  I'm sorry nobody has specifically addressed your issue since it was filed more than a year ago.  But we have made major improvements since then.  If you get a chance to try with Npcap version 0.9991, there is a good chance it will work for you.  And if not, please file a new bug with details and we can investigate.  Thanks!
