### ISSUE TITLE
Upgrade Npcap to NDIS 6.20

### ISSUE THREAD

**Issue by fyodor** [nmap/npcap#167]
Our first step toward upgrading to the latest NDIS version is an upgrade to 6.20.  This one supports all the operating systems that we currently do, and we think/home it may just need a preprocessor symbol definition to upgrade rather than any material code changes.  This is a first step toward eventually supporting NDIS 6.50 for Windows 10. (I'm creating a separate issue for that part)

**Comment by fyodor** [comment]
New Update from @dmiller-nmap: Built 0.9992 with NDIS 6.20 for testing. Build is fine, but loopback capture is messed up. I've isolated the problem (unregistering WFP resources but failing to re-register when they are needed again) but will need a bit more time to make a solution. Idea I have in mind may make listing adapters faster: introduce a new state "open but not capturing" that delays some startup functions until buffer is intialized, since listing adapters results in opening every single one for a moment, but not setting a buffer size.

**Comment by guyharris** [comment]
Speaking of speeding up listing adapters, see also #169.

**Comment by guyharris** [comment]
Note that, with NDIS 6.20, you might have to use `MediaSpecificInformationEx`, rather than `MediaSpecificInformation`, to get the media-specific information on 802.11 adapters in monitor mode.  See [the `NDIS_NET_BUFFER_LIST_INFO enumeration` page](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ne-ndis-_ndis_net_buffer_list_info) and [the `NDIS_NBL_MEDIA_SPECIFIC_INFORMATION_EX structure` page](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/ns-ndis-_ndis_nbl_media_specific_information_ex).

**Comment by dmiller-nmap** [comment]
Accomplished in 59a0625fd49bf745c1e9959e3c652f9a240434bf, but I will check on those OIDs, @guyharris. Thanks!

**Comment by dmiller-nmap** [comment]
Npcap 0.9993 included all changes needed to meet NDIS 6.20 compatibility.
