### ISSUE TITLE
Npcap 0.9992 does not work with latest Wireshark

### ISSUE THREAD

**Issue by vient** [nmap/npcap#183]
I installed Npcap 0.9992 with Wireshark 3.2.4, and while the loopback adapter is still shown in Wireshark, nothing is captured from it. I use Windows 1909, tried two different machines.

I don't know if it is a bug in Npcap or not.

**Comment by guyharris** [comment]
For what it's worth, I'm not seeing it with Wireshark 3.2.4 on W10 1909, although I ended up uninstalling Npcap 0.9992 from the Control Panel and reinstalling it (because the installer warned about not being able to completely uninstall Npcap the first time I tried installing 0.9992 - yes, installer - saying "Failed to completely uninstall Npcap; files in use by: .", with no programs listed after "files in use by:").

**Comment by vient** [comment]
I tried to do it your way (uninstall, reboot, install + reboot), it did not help.

At least I know now that even "Abort" option does not, in fact, abort. All three of them do nothing and continue with installation successfully.

I'm testing loopback with running `ping localhost`, usually it works.

**Comment by dmiller-nmap** [comment]
This bug is fixed in Npcap 0.9993. Due to the way we opportunistically unload the loopback capture mechanism, it was not possible to reload it, so capturing would work until all loopback captures were finished, after which no new loopback captures would work.
