### ISSUE TITLE
warning C4477

### ISSUE THREAD

**Issue by kouzhudong** [nmap/npcap#208]
npcap\packetWin7\WlanHelper\WlanHelper\WlanHelper.cpp(325,13): warning C4477: “wprintf”: 格式字符串“%s”需要类型“wchar_t *”的参数，但可变参数 2 拥有了类型“RPC_WSTR”

			_tprintf(_T("%d. %s\n\tName: %s\n\tDescription: %s\n\tState: %s\n\tOperation Mode: %s\n"),
				i,
				strGuid,
				getAdapterNameFromGuid((TCHAR*) strGuid).c_str(),
				sInfo[i].strInterfaceDescription,
				GetInterfaceStateString(sInfo[i].isState),
				GetInterfaceOperationModeString(ulOperationMode));

不言而喻，不说自明，问题在哪？和如何解决？这个不用我说了吧！

**Comment by guyharris** [comment]
@kouzhudong: I don't know whether Daniel reads Chinese, but English is probably the least incorrect language to use here, as it's the language that most people here are likely to be able to read, either as their first language or their second language.

In any case, Google Translate translates the compiler warning as

    Format string "%s" requires parameters of type "wchar_t *", but variable parameter 2 has type “RPC_WSTR”

Variable parameter 2 is of type `RPC_TSTR`.  Microsoft, annoyingly, didn't define `RPC_TSTR`.

[Microsoft's documentation for `UuidToString()`](https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidtostring) says that its second argument is an `RPC_CSTR *`, but that's probably wrong, given that [Microsoft's documentation for `UuidToStringA()`](https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidtostringa) says its second argument is an `RPC_CSTR *` and [Microsoft's documentation for `UuidToStringW()`](https://docs.microsoft.com/en-us/windows/win32/api/rpcdce/nf-rpcdce-uuidtostringw) says its second argument is an `RPC_WSTR *`, so, if you want to write code that uses DCE RPC routines that deal with strings and that will compile correctly regardless of whether `UNICODE` is defined, one way to do that is to define your own type, `RPC_TSTR` (by analogy to other data types that are `char` strings if `UNICODE` isn't defined and `wchar_t` strings if `UNICODE` is defined) as `RPC_CSTR` if `UNICODE` isn't defined and `RPC_WSTR` if `UNICODE` is defined.

And that's what Npcap does in packetWin7\\WlanHelper\\WlanHelper\\Tool.h.

`RPC_CSTR` is a typedef for `_Null_terminated_ unsigned char __RPC_FAR *`; `RPC_WSTR` is a typedef either for `_Null_terminated_ wchar_t __RPC_FAR *` or `_Null_terminated_ const wchar_t *` (the first if both `RPC_USE_NATIVE_WCHAR` and `_NATIVE_WCHAR_T_DEFINED` are defined, the second otherwise).
I'm also guessing here that "C string" means "null-terminated string of `char`" and "wide string" means "null-terminated string of `wchar_t`".

[Microsoft's documentation for `printf()` and `wprintf()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l?view=vs-2019), `_tprintf()` is either `printf()` if `UNICODE` isn't defined or `wprintf()` if it is defined.  According to [Microsoft's documentation for format strings for `printf()`/`wprintf()`/etc. formatted output functions](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019) says of `%s` that:

> When used with `printf` functions, specifies a single-byte or multi-byte character string; when used with `wprintf` functions, specifies a wide-character string. Characters are displayed up to the first null character or until the precision value is reached.

The problem is that `RPC_CSTR` and `RPC_WSTR` are defined as strings of *unsigned* characters, but `%s` is, with the MSVC library, expecting *signed* characters.  (The PDP-11, and the original C implementation on which, has some stuff to answer for. :-))  Somebody has [some unkind things to say](http://www.flounder.com/msdn_documentation_errors_and_omissions.htm#UuidToString) about Microsoft's choice to define them in terms of unsigned characters.

So that's all the warning is about - passing a string of unsigned octet pairs to a format item that expects a string of signed octet pairs.  Given that a UTF-16 string can have the uppermost bit set in the octet pairs, the handling of the string has to cope with that, meaning avoiding sign extension, so the warning doesn't represent a real problem in this particular case.

Casting `strGuid` to `TCHAR *` would probably suffice to squelch the warning.

**Comment by guyharris** [comment]
> Casting `strGuid` to `TCHAR *` would probably suffice to squelch the warning.

No, it won't, because a `TCHAR` is unsigned, if [Microsoft's Windows Data Types for Strings page](https://docs.microsoft.com/en-us/windows/win32/intl/windows-data-types-for-strings) is to be believed.

If Microsoft don't define their own signed character type, that's 8 bits if `UNICODE` isn't defined and 16 bits if it is defined, in order to squelch this warning, Npcap may have to define its own and cast to a pointer to *that*.

Using a pragma to squelch that warning is another alternative.

**Comment by dmiller-nmap** [comment]
Casting to `TCHAR*` does hide the warning on VS2019, which is good enough for me today.
