### ISSUE TITLE
Npcap driver works abnormally in high concurrent traffic scenarios

### ISSUE THREAD

**Issue by lrh450330** [nmap/npcap#223]
In the past two days, I did a stress test for npcap. It was found that when the network speed exceeded 400Mbps, npcap could not work normally. The number of packets captured was zero for a period of time, and it would run out of memory. I switched wireshake's packet capture and found that the same phenomenon occurred。

**Comment by dmiller-nmap** [comment]
Thanks for this report! We have been working closely with a licensee who was seeing the same issues, and we expect to have a release out to address it soon. The essence of the issue is an integer underflow in the count of "free" space in the kernel buffer, and the fix is in 5abba5e706413d0460c1eb581a50ea5aa95a0680, but there are lots of related changes that will go into the release.

**Comment by dmiller-nmap** [comment]
Npcap 0.9997 resolves this issue. If you find further abnormalities in Npcap 0.9997, please open a new issue. Thanks!
