### ISSUE TITLE
packetRecivepacketerror

### ISSUE THREAD

**Issue by captainretro01** [nmap/npcap#250]
Summary
PacketReceivePacket error

Steps to reproduce
not known

What is the current bug behavior?
an error message is produced saying "Error while capturing packets: PacketReceivePacket error: The device has been removed. (1617)

What is the expected correct behavior?
nothing

Sample capture file
(If possible attach a sample capture file showing this issue)

Relevant logs and/or screenshots
the error code: (''')1617(''')

Build information
Version 3.2.7 (v3.2.7-0-gfb6522d8)

**Comment by captainretro01** [comment]
the npcap version is
Npcap version 0.9997

**Comment by guyharris** [comment]
Did the machine go to sleep (either automatically, or, if it's a laptop, as a result of being closed), with the error popping up when the machine woke up?

On what interface were you capturing?

**Comment by captainretro01** [comment]
@guyharris the pc did not go to sleep, probbaly cuz i have it set not to,
and i was using wireshark

**Comment by guyharris** [comment]
That's `ERROR_DEVICE_REMOVED`.  I'm *guessing* that the NT status `STATUS_DEVICE_REMOVED` maps to the Windows error code `ERROR_DEVICE_REMOVED`.  (Dear Microsoft: where's the secret decoder ring to map between NT statuses that would be used in drivers to Windows error codes?)

`NPF_Read()` returns `STATUS_DEVICE_REMOVED` if no bytes were copied (presumably meaning "no unread packets to return") and `Open->OpenStatus` is `OpenDetached`.  The comment says "Filter module is detached and there are no more packets in the buffer"; what would cause the filter module to be detached?

@bonsaiviking, I seem to remember some discussion between you and somebody at Microsoft about the process of setting up and tearing down the networking stack, and changes they'd made in newer versions of Windows.  Is this related to that?

**Comment by captainretro01** [comment]
@guyharris
do you have a solution to this?

**Comment by guyharris** [comment]
> do you have a solution to this?

I have not looked at that part of the code path in detail, so, no.

**Comment by captainretro01** [comment]
@guyharris if you find one,
just comment it.

**Comment by captainretro01** [comment]
@guyharris
by the way im just the other dude called @captainretro

**Comment by dmiller-nmap** [comment]
Does this happen frequently? What else is going on at the time? Did you lose WiFi connection or unplug a cable? Did you close the laptop lid? Something happened that  caused NDIS to disconnect Npcap from the network stack.

**Comment by captainretro01** [comment]
@dmiller-nmap 1.
this happens everytime i use wireshark after a while
2.nothing really
3.  nope
4.nope
5 no cuz idk what that is

**Comment by captainretro01** [comment]
i think the tor browser is the problem

**Comment by mikedupris** [comment]
Received this error message too.
Windows 10 Ver 1909 build 18363.1198
Npcap 1.00
Wireshark 3.4.0

**Comment by christiankrump** [comment]
Similar issue detected while capturing with an extcap interface.
- npcap V1.00
- pcap_next_ex(...) comes back with the following error-text:
"PacketReceivePacket error: Das Gerät wurde entfernt.  (1617)"

The error appears after a capture duration between 6 and 8 hours!

**Comment by guyharris** [comment]
> while capturing with an extcap interface

If by "extcap interface" you mean a *Wireshark* extcap interface, that must mean that the extcap program is capturing using Npcap and passing the packets to dumpcap over a pipe.

If so, that's a bit odd, given that dumpcap is perfectly capable of capturing using libpcap/Npcap itself.  Is that what you mean?  That might be the case, given that dumpcap doesn't use `pcap_next_ex()`.

**Comment by christiankrump** [comment]
I use some kind of special capture hardware, and I have to extract (decode) the final ethernet frames out of the special decoded frames from my hardware. I think, in this case, I have no other chance than using an extcap interface, which captures these special frames (through npcap), and hand the extracted frames over to the pipe (wireshark).

**Comment by guyharris** [comment]
> I use some kind of special capture hardware, and I have to extract (decode) the final ethernet frames out of the special coded frames from my hardware.

So is your special capture hardware a device that has an NDIS driver, so that it appears as a network interface on the machine running Windows, and thus appears as a network interface to Npcap, or is it a device that transmits the packets in some special format over a regular Ethernet, with your program just capturing packets on a regular Ethernet interface?

**Comment by christiankrump** [comment]
You've described it completeley right in your last comment.
My hardware is a stand-alone device, which transmits special frames through ethernet (defined UDP multicasts). My extcap device listens to exactly these frames, extract/decodes the packed frames, and hands them over to wireshark (pipe).

**Comment by guyharris** [comment]
OK, so the fact that it happens to be an extcap program is irrelevant here; all that matters is that it's a program capturing on an Ethernet interface.

(If the UDP multicasts are to a specific UDP port, note that you could just read them from a socket, and not have to bother with Npcap.  But that's irrelevant to this issue, and should be discussed on a Wireshark mailing list or in a Wireshark issue.)

**Comment by christiankrump** [comment]
I understand what you mean, for sure the workaround with standad sockets would be possible.

But it's fact, that a simple application (using npcap in combination with pcap_next_ex(..) function calls) doesn't work stable.
Do you think about a solution in the near future?

**Comment by guyharris** [comment]
> But it's fact, that a simple application (using npcap in combination with pcap_next_ex(..) function calls) doesn't work stable.

Yes, that's why this bug was filed.  (And it has nothing to do with what calls are used; Wireshark's dumpcap doesn't use `pcap_next_ex()`, it uses `pcap_dispatch()`, but they get the same problem.)

> Do you think about a solution in the near future?

I don't know what the cause is; you'd have to ask @dmiller-nmap what the likely cause is and what would have to be done to fix it.

**Comment by dmiller-nmap** [comment]
The only code path in Npcap that can result in this code (1617 = ERROR_DEVICE_REMOVED) after a device has been opened successfully is if NDIS detaches Npcap from an adapter. This can happen as a result of certain network stack modifications such as the installation of another filter driver. Npcap's installation tool can replicate this behavior by re-binding Npcap to the stack, which causes a full detach/reattach. The command to do this is `NPFInstall.exe -r2`

This is entirely out of Npcap's control. It *may* be possible in the future to keep capture handles around until the filter driver is reattached to the adapter, but that would involve a significant amount of research and development. The biggest challenge immediately obvious is that we do not know at the time the filter is detached whether the adapter has been removed or whether something else has happened, so user programs could be kept waiting for a network that will never return.

@guyharris Since this is a known issue, could we perhaps have Wireshark not suggest that users file bug reports here for this error code (1617)?

**Comment by guyharris** [comment]
@dmiller-nmap I seem to remember somebody from Microsoft commenting, at some point, about the way Windows dismantles the networking stack on a sleep and reconstructs it when waking up, and talking about changes they were making to fix some issues with it.  It may have been in response to something you asked; I forget whether it was here, an issue list for some Microsoft project, or some Microsoft forum.

Do you remember any such discussion?

**Comment by dmiller-nmap** [comment]
@guyharris Yes, that was Jeffrey Tippet, and he was referring to interruptions to the stack that may happen when a filter driver is installed. Npcap was causing RDP and other connections to drop when it was installed, but only in certain instances. MS updated some internal NDIS logic to make it much less likely that such a thing would happen, but it still can. Npcap "tolerates" this in that it doesn't crash or leave capture handles in some limbo state, but it does unfortunately invalidate them, for the reasons discussed above.

**Comment by guyharris** [comment]
So does the network stack really get completely dismantled on a sleep and reconstructed on a wakeup, so that any form of packet capture that doesn't somehow avoid the networking stack will be disrupted?

**Comment by dmiller-nmap** [comment]
@guyharris "completely dismantled" is overstating it; I think it's just certain parts of NDIS like the filter drivers. And no, it's not done for an ordinary sleep. I don't have an exhaustive list of the things that cause it, but installing filter drivers can require it in some cases. Full discussion here: https://github.com/nmap/npcap/issues/53#issuecomment-657812288

**Comment by guyharris** [comment]
> it's not done for an ordinary sleep. I don't have an exhaustive list of the things that cause it, but installing filter drivers can require it in some cases.

I suspect, in most of these cases, manually installing new software isn't causing the disruption.

My question is "what *does* cause it?", so that I can change the Wireshark error message to tell users, in the secondary text for the error dialog, what *not* to do while capturing, so they don't report this as a bug at all, they just do whatever's necessary to keep it from happening.

**Comment by guyharris** [comment]
@jtippet, any idea what would cause a filter driver such as Npcap to be detached from an adapter if nobody is installing or uninstalling any software that would add to or remove from the filter driver stack?

**Comment by jtippet** [comment]
Yeah NDIS reserves the right to detach LWFs at any time, for its own internal reasons.  Although NDIS's goal is that this is a transient state: the natural state and the pull of gravity is towards every filter being attached.

If your LWF is detached for some reason, you probably aren't missing out on much: NDIS guarantees that data *will not flow* unless your driver is attached, or unless it's not even running (`NdisFRegisterFilterDriver`).  For LWFs flagged as Mandatory in the INF, NDIS makes the stronger guarantee that data will not flow unless your driver is running *and* attached.

Anyway, in the current version of NDIS, NDIS may detach a LWF for a variety of reasons:

* someone unbound the LWF, e.g. with `Disable-NetAdapterBinding` or the underlying `INetCfg` call
* the LWF has called NdisFDeregisterFilterDriver (typically because the driver is unloading)
* a lower LWF is marked as Mandatory, and that lower LWF is detached for some reason (during the first 60 seconds of boot, even Optional LWFs are considered temporarily Mandatory -- this is a very obscure implementation detail that I might change someday, so don't take a dependency on it)
* each instance of a Monitoring LWF is associated with an instance of a Modifying LWF (it's complicated), so if you have a Monitoring LWF, it will get detached if its associated Modifying LWF is detached for some reason.  But, you are guaranteed your 0000th instance is associated with the miniport itself, so that lowest instance will not be detached at the whim of any other LWF.
* some lower LWF is attaching/detaching, and it has the UnbindOnAttach/UnbindOnDetach flags set.  By default, all Mandatory LWFs have both flags set.
* some types of miniport don't natively support power states, in which case NDIS tears down the whole miniport stack during a system power transition.
* the miniport itself is halting for any reason, e.g., `Restart-NetAdapter` or an `IRP_MN_STOP_DEVICE` or a surprise removal (e.g. user yanks out USB adapter) 
* the miniport has disabled its default `NDIS_PORT` (`NetEventPortDeactivation` on the default port).  This is rarely used.
* the miniport or a lower LWF has indicated `NetEventInhibitBindsAbove`
* the miniport or a lower LWF has indicated a "deep" change to its MAC layer, like `NDIS_STATUS_CURRENT_MAC_ADDRESS_CHANGE` or `NDIS_STATUS_L2_MTU_SIZE_CHANGE`, and your LWF has not specifically opted-in to supporting such a change.  note that as a combination of this rule and some previous rules, you are likely to get detached if *any* LWF below you does not opt-in to these types of changes.

As you can see, there's a lot of reasons that NDIS can detach a LWF, and that list will certainly evolve over time.  If you need to make the pcap API robust against ephemeral detaches, I suggest adding a layer of indireciton/abstraction between the notion of a LWF being attached and a handle visible to the usermode pcap API.

**Comment by guyharris** [comment]
> Anyway, in the current version of NDIS, NDIS may detach a LWF for a variety of reasons:

Those seem to fall into several categories:

* an event probably caused by the user taking some action, e.g. `Disable-NetAdapterBinding` which sounds like something you'd type at PowerShell;
* some reorganization of the filter stack, provoked by something not necessarily requested by the user, e.g. "the LWF has called NdisFDeregisterFilterDriver (typically because the driver is unloading)" and "a lower LWF is marked as Mandatory, and that lower LWF is detached for some reason";
* something the miniport driver did.

For the first of those, we just tell the user "well, don't do that if you want the capture to continue".

For the second of those, if it's something user-initiated, such as unload the NPF driver, we just tell the user "well, don't do that if you want the capture to continue".  For the others, what might trigger such a reorganization?

For the third of those:

- "some types of miniport don't natively support power states, in which case NDIS tears down the whole miniport stack during a system power transition." - if they have that type of miniport, the answer is again "well, don't do that if you want the capture to continue".  Don't let the machine sleep or hibernate (which, if they're doing a passive capture, they don't want to happen anyway).  What types of miniport are those?
- "the miniport or a lower LWF has indicated `NetEventInhibitBindsAbove`" - that sounds, from [the docs.microsoft.com page for `NET_PNP_EVENT`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/netpnp/ns-netpnp-_net_pnp_event), like something the miniport driver might do while the machine is awakening from a sleep or hibernate; is that the case?
- "the miniport or a lower LWF has indicated a "deep" change to its MAC layer, like `NDIS_STATUS_CURRENT_MAC_ADDRESS_CHANGE` or `NDIS_STATUS_L2_MTU_SIZE_CHANGE`, and your LWF has not specifically opted-in to supporting such a change."  I don't see those documented on docs.microsoft.com, and neither sounds as if it's something that should affect the NPF driver (the former *might* want to cause the *application* to change a capture filter, but the semantics of packet filtering in pcap don't include "oh, and you can request a match against the adapter's *current* address", so it's not pcap's job to respond to that), so perhaps the NPF driver should opt in to supporting that change.

> If you need to make the pcap API robust against ephemeral detaches, I suggest adding a layer of indireciton/abstraction between the notion of a LWF being attached and a handle visible to the usermode pcap API.

If we can't guarantee that some spontaneously-generated (as opposed to user-generated) event won't cause an ephemeral detach, that might be our best choice.  I think #506 is about that.

**Comment by jtippet** [comment]
I'm not really in a position to comment on *why* some LWF might decide to deregister itself, or why a LWF or miniport might invoke `NetEventInhibitBindsAbove`.  We just provide the APIs, and everyone else does cool stuff with them.  I wouldn't expect a PC that's sitting idle to be changing its bindings, but nothing stops a 3rd party from shipping a crazy LWF that attaches+detaches itself every 60 seconds, for some bizarre reason.

After all, pcap itself injects itself into the network stack when the user launches some application -- nothing prevents some other 3rd party software package from doing something similar.

>  I don't see those documented on docs.microsoft.com

Sorry, that's on my to-do list.  The MAC Address change is mostly used internally by the OS, when implementing the MAC Address Randomization feature for WiFi, so we haven't had a lot of urgency to write the docs for it yet.

> and neither sounds as if it's something that should affect the NPF driver

If you cache the MAC address anywhere, it would affect you, but many LWFs do not care about the MAC address.  The MTU would probably affect more LWFs: if you allocate buffers to hold packets, those might need to be reallocated if the MTU has increased.

**Comment by guyharris** [comment]
> After all, pcap itself injects itself into the network stack when the user launches some application

So Npcap adds itself to the filter stack when a device is opened?

What I'm trying to do here is figure out what to say in the secondary text of the Wireshark error dialog for this condition (I guess it's the "Contents" part, rather than the "Title" part, as described on [the UWP "Dialog controls" page](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs); [Apple calls it the "Informative text"](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/)).

It sounds as if, in some cases, this Just Happens and there's not much that can easily be done about it - it might be some other software installed on the user's machine, without some good way of even finding out what the software is, much less some good way of getting it fixed, and they might not be able to remove it.

In some cases, "don't let the machine go to sleep" might be a good recommendation (if they're doing passive capture, it's *definitely* a good recommendation, as if the capturing machine goes to sleep it might miss traffic that the user would want to capture), but it doesn't sound as if that's sufficient to prevent it from ever happening.

**Comment by dmiller-nmap** [comment]
@guyharris Npcap adds itself to the filter stack as soon as the driver service starts (at boot). Opening a handle to the Npcap device (or "a device" in the Packet.dll API) inserts a context (`OPEN_INSTANCE`) into a list that may or may not receive some of the traffic that the Npcap driver is passing through. But the traffic always passes through, even if user software isn't receiving any of it, and we don't mess with the stack directly.

You are correct, #506 is about this. The filter module (NDIS LWF component attached to the stack) and the user context (device handle, `OPEN_INSTANCE` struct) are related, but they don't require each other to exist. We already detach the filter module from any user contexts when the NDIS FilterDetach happens (destroying the filter module). The only remaining part to implement is reattaching to the new filter module when FilterAttach happens for the same adapter. We might not even have to implement a timeout in the driver if user code (libpcap or whatever's using it) can just keep trying again after the "error 1617." That would leave it up to the user code to decide when to give up.

**Comment by guyharris** [comment]
> user code (libpcap or whatever's using it) can just keep trying again after the "error 1617."

Thanks for reminding me of something that really annoys me about the Linux networking stack. :-)

Most if not all systems that use the BPF capturing mechanism return a read error (ENXIO or EIO, depending on which system) if a device is removed, and don't return an error if the device is configured down.

Linux PF_PACKET sockets, however, return a one-shot error if the device is configured down, and don't deliver a subsequent error if it disappears.  We do *not* want to stop capturing if the device is configured down, as it might be configured up again later, but *do* want to stop capturing if the device disappears, as that means we will never get another packet from it ever again.  libpcap handles this by treating a "configured down" indication as a hint that the device *might* have disappeared, not indicating anything to the caller, but setting a flag that causes it to periodically check whether the device has gone away.  That flag remains set until either 1) we detect that the device has disappeared or 2) we detect that it is still around because it's back up.

So there's precedent for something such as that.
