### ISSUE TITLE
Npcap 0.9990: Disrupts loopback connectivity/consumes whole core on WS2016

### ISSUE THREAD

**Issue by akontsevoy** [nmap/npcap#26]
Greetings,

We have reports from multiple users that Npcap version 0.9990 intermittently disrupts connectivity on the loopback interface (causing connections made on 127.0.0.1 to time out). The issue seems isolated to Windows Server 2016, with isolated reports for WS2019. When it happens, the System process is seen to consume a whole CPU. The problem is resolved when Npcap is downgraded to 0.993 (the version we bundled previously). Has this been a known issue, possibly addressed in 0.9991? The similar issues I'm finding are either Windows 10 or Windows 7.

P.S. This happens despite our software not capturing anything from NPF_Loopback (not even opening a pcap handle on that adapter).

**Comment by akontsevoy** [comment]
@dmiller-nmap This happens to remediate the leak on WS2016 where it was originally reported, but on W10 1909 the leak still reproduces as of 0.9991 (and even 0.993 which did not have loopback capture functionality in that form). So this must not be the only leak in that mess of a function...

**Comment by guyharris** [comment]
I've filed #169 for the interface-enumeration changes I mentioned.

**Comment by fyodor** [comment]
Dan (@dmiller-nmap) had some great notes on this when we chatted today: "I've tried in the past to make the loopback initialization functions conditional on actually needing them, but it didn't work exactly right, so I ended up backing those changes off a bit. The changes I've made recently are the latest attempt. We really want to avoid registering all our WFP resources until they're really needed, because some people have problems if that's even touched. But for some reason, it seems the registration doesn't work. I've got a debugger paused at the moment about to find out if the very first registration works and subsequent ones fail, or what. But #169 may allow us to back out these changes and still keep most of the benefit. Because it wouldn't matter very much if everything gets initialized right away when you open an adapter except that each adapter gets opened multiple times in a single pcap_findalldevs() call. So what I'm envisioning based on Guy's suggestions is this:
1. we go through Packet.dll and reduce the adapter discovery routines for NPF and IPH (IP Helper API) to a single routine, keeping track of what information is discovered there.
2. Replace the GetAdaptersAddresses() and Registry stuff with a IoControl that the driver can answer with the information it already has on hand.
3. Implement a way to handle a CreateFile (Open) call for a special name like \Devices\NPF_Info that can handle this new IoControl but not any of the other capture stuff.

**Comment by guyharris** [comment]
> 2. Replace the GetAdaptersAddresses() and Registry stuff with a IoControl that the driver can answer with the information it already has on hand.

So the per-interface information that libpcap currently uses *or* may use in the future is:

- the name to use in `pcap_open_live()`/`pcap_open()`/`pcap_create()`;
- the "friendly name" (that's what Microsoft calls it);
- the "description" (hardware description);
- the MAC address;
- the transmit and receive link speeds;
- all the IPv4 and IPv6 addresses, netmasks, and broadcast addresses assigned to the adapter;
- something that can be mapped to a value like the UN\*X "UP" and "RUNNING" flags - the libpcap master branch's pcap-npf.c maps the result of `OID_GEN_HARDWARE_STATUS` to those flags;
- the time stamp types supported by the adapter (currently the same for all adapters, and dependent on whether the kernel provides high-precision values of the system clock, but if Microsoft ever supports getting packet time stamps from adapters that support it, that should also be provided);
- the NdisMediumXXX value for the adapter;
- *if* the adapter can support monitor mode, the NdisMediumXXX value that would be used in monitor mode, otherwise a "no monitor mode" indication.

If there were both an ioctl - and corresponding packet.dll routine, unless you decide to directly expose the BIOC ioctls and a routine to allow direct ioctl calls - to get the information for all adapters *and* a routine to get the information only for the currently open adapter, that would be useful (either now or in the future).

**Comment by fyodor** [comment]
From chat with @dmiller-nmap today: "We partially addressed this in Npcap 0.9992 by gating off the loopback functionality, but there's still a chance that if someone explicitly started a loopback capture there it would have the same result. It's possible even a MODE_STAT capture (just packet statistics) could trigger it, like Wireshark uses for their sparkline graphs. We just really don't know what the underlying cause is. Who knows, was a weird interaction between the WFP callback stuff and the worker thread queue that only existed in 0.9991."

So we're leaving this open for now and watching to see whether we get further reports that we can investigate.

**Comment by guyharris** [comment]
> From chat with @dmiller-nmap today: "We partially addressed this in Npcap 0.9992 by gating off the loopback functionality, but there's still a chance that if someone explicitly started a loopback capture there it would have the same result. It's possible even a MODE_STAT capture (just packet statistics) could trigger it, like Wireshark uses for their sparkline graphs.

Wireshark doesn't use MODE_STAT for the sparklines; it uses regular capture and, for each packet seen, just counts it, and the counts are used for the sparklines.  (It has to work on UN\*X, so it has to work on platforms without `pcap_setmode()`, so the code to do that had to be written anyway.)

**Comment by dmiller-nmap** [comment]
I wish I could have found this before Npcap 0.9995, but it'll be fixed in next release.
