### ISSUE TITLE
Npcap Loopback Adapter doesn't appear in Network Connections

### ISSUE THREAD

**Issue by DavidA2014** [nmap/npcap#262]
Since upgrading from Npcap v0.99 to v1.00, Npcap Loopback Adapter no longer appears in Network Connections in Windows 10. Is that expected behaviour?

**Comment by sky5454** [comment]
![图片](https://user-images.githubusercontent.com/12370628/99905683-55120080-2d0d-11eb-886f-ef591296bfde.png)
Here

**Comment by dmiller-nmap** [comment]
Npcap Loopback Adapter was needed for loopback capture in Npcap prior to 0.9983, but it frequently caused problems with other network software such as firewalls and VPNs. Because of this, we removed the need for it; loopback capture is now performed via the "Adapter for loopback capture" device (`\Device\NPF_Loopback`), which does not show up in Network Connections (since it is not a network connection). It is still possible to install the Npcap Loopback Adapter, though to my knowledge only Nmap 7.80 and earlier require it; this is the "Legacy loopback capture" installation option.

**Comment by DavidA2014** [comment]
Thanks for your answer
