### ISSUE TITLE
Broken installations due to #268 continue to crash on upgrade attempts.

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#280]
As reported in nmap/nmap#2210, the fix for #268 (do not replace the uninstaller) does not help on systems where the crash was previously triggered, because the original uninstaller has already been replaced with one that triggers the bug.

Workaround: prior to running an upgrade to Npcap 1.10 on such systems, manually stop the `npcap` driver service (as Administrator run `net stop npcap`)

**Comment by daulis** [comment]
@dmiller-nmap I believe there have been similar issues in the past (https://www.wireshark.org/docs/relnotes/wireshark-3.0.5.html#npcap_upgrade) where upgrading from one version to another causes a BSOD, and the workaround was to manually stop the npcap driver, before installing the new one. I know that I've personally seen a BSOD during an upgrade scenario awhile ago (although I don't remember the versions)

I don't know the details of the install/uninstall procedure, but could all future installers just do `net stop npcap` before running the other uninstaller that was already on the PC? It seems like this would prevent the issue, regardless of what old version that you were upgrading from.

One of our users at work ran into (I think) the same BSOD yesterday on a remote PC, and it was pretty difficult to recover from since we are all working remote. In their case, they were upgrading from 0.9987-oem to 1.00-oem. If you think it might be something other than https://github.com/nmap/npcap/issues/268, then let me know, and I can try to get some additional data.

**Comment by dmiller-nmap** [comment]
@daulis Thanks for the suggestion. Unfortunately, the reason we can't just stop the driver ourselves is because the driver will not stop if some process has an open handle to it. Because of this, our uninstaller tries to find and terminate such processes. We recently enhanced it to query the driver directly for process IDs that have open handles, which is a big improvement, but this is exactly the operation that triggers the bug in older drivers. It's a catch-22.

Fortunately, we have some further improvements planned to clean up these old, broken installations, which we will roll out in newer releases.

**Comment by daulis** [comment]
@dmiller-nmap A couple other things (again, with me knowing nothing about the complexities involved in uninstall/install).

It would be nice if most/all of the cleanup/shutdown logic was also at the beginning of the installer, instead of just the uninstaller. That way, if there is later a bug in the uninstaller, you can prevent it by just updating the next release's installer. I think a lot of times, there are some assumptions made that users often upgrade each version when available. But, as I see the installation habits of users at my company, people often skip many intermediate releases, which I think exposes some of these issues.
Testing all the various combinations of upgrading to different versions isn't really feasible, so that's another benefit of having the latest installer have the most comprehensive cleanup logic. 

You may already have all the info you need, so I'm not sure if this helps. But, here is the sequence that my user had:
1. 0.9987-oem was installed
2. Attempted to upgrade to 1.00-oem. But, this BSODed
3. Attempted to upgrade to 1.10-oem, but the 1.00 uninstall failed. (It looks like 1.00-oem was partially installed) See: ![npcap-1 00-uninstall-failed](https://user-images.githubusercontent.com/6913228/104370018-43b6ca80-54ec-11eb-9713-62fdf3492441.png)
4. User hit Cancel, and tried to use Wireshark. But, it looks like most of Npcap was removed. Wireshark GUI showed `Unable to load Npcap or WinPcap...`.
5. User then went to Add Remove Programs based on the Wireshark error message, but it shows Npcap was already installed (which is confusing). 
6. User then tried public Npcap 1.10, and that worked. (I assume if they retried the 1.10-oem that also would have worked).

**Comment by dmiller-nmap** [comment]
We now have a solution in several parts, pending testing:

1. e15bf7b51fae4a70928326319f248bd0b124f434 - NPFInstall.exe will use Loopback device instead of blank device name when opening a driver handle in order to enumerate PIDs with open handles. This change prevents new installer/uninstaller from crashing Npcap before 0.9988 (#268).
2. 1ee49c2a5bb0477e0fade548b2fe397e4c553961 - NPFInstall.exe will check for processes which have the renamed-prior-to-delete DLLs open, since these likely have open handles. This fixes a detection failure that existed between 0.9991 and 0.9994.
3. nmap/npcap-build@6ff51bb040a67e1d322477cfe97de7ca144170ea - Before running the uninstaller, the installer will disable the driver service in the Registry, preventing it from restarting at next boot unless it is replaced. This way, a buggy driver will be prevented from starting after a crash caused by an installer, so the next invocation of the installer will be able to safely replace it without crashing.

**Comment by dmiller-nmap** [comment]
Fixed in Npcap 1.20
