### ISSUE TITLE
pcap_setmintocopy returns (-3)

### ISSUE THREAD

**Issue by ardikars** [nmap/npcap#283]
When I call pcap_setmintocopy(p, 1) on inactive-capture it always returns (-3), what does it means? Should I ignore it?
I've tested it on:
* WinPcap version 4.1.2 (packet.dll version 4.1.0.2001), based on libpcap version 1.0 branch 1_0_rel0b (20091008)
* Npcap version: Npcap version 0.9982, based on libpcap version 1.9.1-PRE-GIT
and got the same result.

```c
#include <pcap.h>
#include <stdlib.h>

int main() {
        char errbuf[PCAP_ERRBUF_SIZE];
        pcap_t *p = pcap_create("\\Device\\NPF_{BBD03DA0-5C9F-4865-804E-86F6CD8275BE}", errbuf);
        if (p == NULL) {
                exit(EXIT_FAILURE);
        }
        if (pcap_set_snaplen(p, 65535) != 0) {
                exit(EXIT_FAILURE);
        }
        if (pcap_set_promisc(p, 1) != 0) {
                exit(EXIT_FAILURE);
        }
        if (pcap_set_timeout(p, 1) != 0) {
                exit(EXIT_FAILURE);
        }
        int rc = pcap_setmintocopy(p, 1);
        printf("rc = %d\n", rc); // returns -3
        rc = pcap_setmintocopy(p, 16000); // default value
        printf("rc = %d\n", rc); // returns -3
        pcap_close(p);
        return 0;
}
```
Thanks.

**Comment by guyharris** [comment]
> When I call pcap_setmintocopy(p, 1) on inactive-capture it always returns (-3), what does it means?

To quote the `pcap.h` header file:

    #define PCAP_ERROR_NOT_ACTIVATED	-3	/* the capture needs to be activated */

I.e., it means "you tried to call `pcap_setmintocopy()` on an inactive capture."

> Should I ignore it?

No, you should call `pcap_setmintocopy()` *after* calling `pcap_activate()`.

Libpcap could be changed to allow it to be called before activation - it would save the value and then set it after there's a handle on which *to* set it - but that would mean that, if the minimum-to-copy value was invalid, `pcap_activate()` would return an error and fail to activate the device, and it wouldn't be obvious that the error was that the minimum-to-copy value was invalid (or that some other unexpected error occurred).

Furthermore, that would only fix it in versions of Npcap that picked up whatever new release of libpcap had that change; it wouldn't fix older versions of Npcap, and it wouldn't fix WinPcap (which isn't being developed any more).

So it's probably best  to defer setting the minimum-to-copy until after activating the device.

Also, it's best to handle unknown error codes by reporting them with `pcap_statustostr()`:

    int rc = pcap_setmintocopy(p, 1);
    if (rc != 0)
        printf("rc = %s\n", pcap_statustostr(rc));

as that will report a message indicating what the problem is, rather than reporting a number that you'd have to look up in pcap.h to see what it means.

**Comment by guyharris** [comment]
> but that would mean that, if the minimum-to-copy value was invalid, `pcap_activate()` would return an error and fail to activate the device, and it wouldn't be obvious that the error was that the minimum-to-copy value was invalid (or that some other unexpected error occurred).

Or it could return `PCAP_ERROR` (-1) and supply a string that indicates that the problem was with setting the minimum-to-copy value.

**Comment by ardikars** [comment]
Thank you for the explanation @guyharris . I'll close this issue.
