### ISSUE TITLE
Unable to capture packets on Surface Mobile Broadband adaptor

### ISSUE THREAD

**Issue by joelg989** [nmap/npcap#303]
Driver version: 12.35.25.169
Windows version: Windows 10 Pro 20H2 19024.928
Wireshark version: 3.4.4
Npcap version: 1.30
Device: Microsoft Surface Pro 5 with LTE

Issue does not affect packet capture over WiFi
Issue occurs for both Administrators and non-Administrators.
Issue occurs for both promiscuous and non-promiscuous adaptor setting.

The Npcap Packet Driver appears correctly on the interface. Error message: "The capture session could not be initiated on interface '<redacted>' (failed to set hardware filter to non-promiscuous mode: Couldn't get message for error (3758096571)). Please check to make sure you have sufficient permissions, and that you have the proper interface or pipe specified. "

The Wireshark people think this is an issue with npcap.

**Comment by guyharris** [comment]
3758096571 = 0xE00000BB.  That looks suspiciously like an *NT* error status, rather than a *Windows* error status.  If so, as per [the layout of NTSTATUS values](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/87fba13e-bf06-450e-83b1-9241dc81e781), that's STATUS_SEVERITY_ERROR plus the C bit:

> C (1 bit): Customer. This specifies if the value is customer- or Microsoft-defined. This bit is set for customer-defined values and clear for Microsoft-defined values.[<3>](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/1714a7aa-8e53-4076-8f8d-75073b780a41#Appendix_A_3)

and footnote 3 says "All NTSTATUS values that are used by Microsoft have the **C** bit clear."

Is this Microsoft's way of saying "hey, we market the device under our name, and did at least some of the hardware design work, but didn't write the driver, it's not *our* fault*?

This is a giant bag of annoying - it returns some random *private* error code, so there's precisely zero explanation of *why* it rejects attempts to set the `OID_GEN_CURRENT_PACKET_FILTER` OID.  Microsoft might want to explain to the driver developers for their device what the word "mandatory" means in the text i[n the page about the `OID_GEN_CURRENT_PACKET_FILTER` OID](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-current-packet-filter).

I guess the least bad fix would be to check for 0xE00000BB in pcap-npf.c and just ignore it; "promiscuous" doesn't apply to non-broadcast networks.

**Comment by joelg989** [comment]
Since testing this is presumably a massive pain for anyone who doesn't own this exact device, I'll try building npcap from source with the proposed fix to test that it works.

**Comment by joelg989** [comment]
I'm trying to test this, and while I've built npcap from source, I'm having trouble installing it.  Is there any documentation on installing a build (and verifying the installation)?

**Comment by guyharris** [comment]
"Npcap" is a mix of two code bases:

- the libpcap library, which provides the APIs to callers and implements all the stuff that's not packet capture atop the NT kernel code;
- the Npcap driver and the packet.dll user-mode library that uses it.

On UN\*Xes, the OS provides a packet capture mechanism, and libpcap uses that.  Windows doesn't, which is why WinPcap was created - it adds kernel-mode code (the driver) and a user-mode library to communicate with the driver, and adds a file to libpcap to do packet capture on Windows, calling the user-mode library.

Npcap has the same structure, although the driver is significantly different (it plugs into a different place in the networking stack, which was first made available in Vista; for most purposes, that works better than the way the WinPcap driver plugged in).  It's also based on a much newer version of libpcap, which has picked up all the changes that WinPcap made, so the standard libpcap can be used.

Npcap has its version of libpcap (which includes some not-yet-in-a-libpcap-release fixes to problems seen by Npcap).  It's in its own repository, separate from the Npcap repository, and forked from the main libpcap repository; it's at https://github.com/nmap/libpcap.

It currently doesn't include the "least bad fix" referred to.

Standalone builds of libpcap-on-Windows aren't that difficult; see, for example, https://github.com/nmap/libpcap/blob/master/doc/README.Win32.md.  For testing, you'll need to copy the pcap.dll that it builds, replacing the wpcap.dll on your system.

**Comment by joelg989** [comment]
Just to clarify, if I want to submit a pull request, should I be doing it to mainline libpcap, not to the nmap fork?

**Comment by guyharris** [comment]
> if I want to submit a pull request, should I be doing it to mainline libpcap, not to the nmap fork?

If it's a change to a libpcap file such as pcap-npf.c, yes, submit it to mainline libpcap, so it won't be a difference between mainline libpcap and the nmap fork that will have to be maintained forever.  Daniel can pick it up for the fork so it can show up in Npcap before it shows up in a main libpcap release.

**Comment by dmiller-nmap** [comment]
Npcap itself is setting the "custom bit" in the error code as part of the SET_FAILURE_CUSTOM macro in Packet.c. We already avoid setting this OID for Native WiFi adapters for some reason (the raw 802.11 frame capture installation option), so that could be a possibility. We're looking into what options are available and why this OID might be being rejected on these adapters. Another report came to us privately of the same behavior with an Intel LTE adapter.

**Comment by guyharris** [comment]
OK, so if we strip out the customer bit, we get 0xC00000BB, which is `STATUS_NOT_SUPPORTED`.

Is the idea that you don't want kernel32.dll to map NT status values to Windows error codes, so that information isn't lost, so you protect them by setting the customer bit?  Perhaps libpcap should check for anything that looks like an NT status value with the customer bit set, strip off the customer bit, and check for some values and report them with a status-specific message, reporting all of them with the NT status in hex?

**Comment by dmiller-nmap** [comment]
The outcome of the-tcpdump-group/libpcap#1010 was applied to Npcap's release branch prior to Npcap 1.50, so you should be able to use Npcap 1.50 to capture on this adapter now.
