### ISSUE TITLE
Investigate removing WSK from Loopback packet injection data path

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#307]
Currently, injecting loopback traffic involves:

1. Wrapping the packets in a false IPv4 header,
2. Sending them with Winsock Kernel (WSK) sockets
3. Detecting the false header in the loopback WFP filter
4. Removing the false header
5. Injecting the original packet via WFP injection handles.

I think we could cut out steps 1-4 and just inject with the WFP injection handles. I need to investigate whether that would work.

Original commit introducing this data path: 1fb4a0807e060be1564a1d6b0085ded3b4cd53d5

**Comment by fyodor** [comment]
Here's some more detailed background that @bonsaiviking  wrote to me in chat:
* WSK is "WinSock Kernel" and is a way to get a socket-like API within kernel-mode driver code.
* WFP is Windows Filtering Platform, and is a (relatively) simple API for filtering network traffic.

We use WFP to capture loopback traffic, since that doesn't enter the NDIS stack where the primary capture part of Npcap sits (the Lightweight Filter driver). When user code injects packets, the packets come in via a Write() system call to the Npcap driver's device handle. If it's a capture handle for a normal interface, we use NDIS functions to inject the traffic directly where it belongs. If it's a loopback capture handle, we currently wrap the packets in a fake IP header with a "special value" for the IP protocol field and send them using WSK. The loopback capture mechanism sees the traffic, identifies the "special value", strips off the fake IP header, and injects the traffic using WFP packet injection functions. I want to see whether we can cut out the middleman and just inject the traffic directly with the WFP packet injection functions as soon as it comes in via the Write() system call. I suspect there may have been trouble doing this in the past due to some convoluted code that was used to clone the network traffic. That has largely been streamlined now, and the bugs worked out. I think it's time to try it again.
