### ISSUE TITLE
npcap 0.95 - duplicate sent-out packets seen on local Interface

### ISSUE THREAD

**Issue by mapl** [nmap/npcap#399]
Hello,

when I start Wireshark I am encountering duplicate TCP/UDP packets sent from my machine . After toggling the NPcap driver in the TCP/IP Settings of my Ethernet Interface and restarting Wireshark, the behavior is not seen anymore until I restart the System.

Is this behavior already known or limited to my machine?

OS: Windows 10 Build 1706
Wireshark 2.4.2

**Comment by mikefjim** [comment]
Hi

I've just tested Wireshark with the inbuilt Npcap 1.72 and also the last version 1.76 and this issue is not solved. Sent telegrams our always shown duplicated on the computer where npcap is running, on a secondary computer receiving traffic, no duplicates are seeing. I tested with 2 different computers.
then uninstalled everything and installed an old version of Wireshark with the last Winpcap driver, and it works just fine. 

Is there anywhere else to address this?

**Comment by guyharris** [comment]
> Sent telegrams our always shown duplicated on the computer where npcap is running, on a secondary computer receiving traffic, no duplicates are seeing.

So it's not as if two packets are being sent out on the network adapter.

By "shown duplicated on the computer where npcap is running", do you mean they show up twice in Wireshark, or do they show up other than in packet sniffers running on that computer?

**Comment by mikefjim** [comment]
Hi

all outgoing packets from the computer where wireshark is running are duplicate. It can be from simple ICMP requests (ping) to other protocols I'm testing. 
These duplicates are not real, as the  receiving computer only sees one packet

**Comment by guyharris** [comment]
> all outgoing packets from the computer where wireshark is running are duplicate. It can be from simple ICMP requests (ping) 

So if  you do `ping /n 1 {remote host}` while Wireshark is running, Wireshark shows *two identical* ICMP echo requests from your host?

**Comment by mikefjim** [comment]
yes

**Comment by guyharris** [comment]
Definitely duplicates, then; you're supposed to see *one* copy of transmitted packets from libpcap/WinPcap/Npcap.

@dmiller-nmap, should this be reopened, or is this probably caused by another problem, so that a separate issue should be filed?

**Comment by mikefjim** [comment]
Maybe this information will help. I have VMWare installed on all 3 computers I tested both ncap and Winpcap.

As I mentioned, when Winpcap is installed, I dont see the output duplicates. But, if an image in VMWare is running, then I see the duplicates even with Winpcap. The duplicates can be seen on Wireshark running inside the image or on the host computer. I already saw that this is normal for VMWare and using NAT virtual NIC, instead of the bridge should solve it..
Could it be that just because I have VMWare installed, even if not running, is causing issues on npcap?
