### ISSUE TITLE
Npcap Bug Report - Can't Get the LinkSpeed

### ISSUE THREAD

**Issue by liujingliangPacs** [nmap/npcap#40]
1. Use the WinPCap 4.1.3
    I can retrieve the network speed with the following code.
2. Use the current Npcap "npcap-0.9984.exe"
    There are 12 adapters in my win7 system.
    But only 1 adapter's link speed can retrieved.
    Following are all the adapters:
    1 - \Device\NPF_Loopback, speed = 10000000
    2 - \Device\NPF_{ D2F5FDB8 - 026D - 4E3C - 9603 - E0847AF4A334 }, speed = 0
    3 - \Device\NPF_{ 35E23E0A - 1D3B - 4BA8 - B1A3 - BFB5D407AFB1 }, speed = 0
    4 - \Device\NPF_{ A656415F - 88BE - 4CD1 - 8596 - C736CAFF67AC }, speed = 0
    5 - \Device\NPF_{ 23BD7BB6 - 5321 - 441B - 903A - 27418CBC8569 }, speed = 0
    6 - \Device\NPF_{ F37FB154 - 95B3 - 4047 - AA98 - F75C3DEC5285 }, speed = 0
    7 - \Device\NPF_{ A05D7D3F - 257C - 4D2F - 867A - E821A94B548C }, speed = 0
    8 - \Device\NPF_{ 78032B7E - 4968 - 42D3 - 9F37 - 287EA86C0AAA }, speed = 0
    9 - \Device\NPF_NdisWanIp, speed = 0
    10 - \Device\NPF_{ 4D3329D0 - 7D57 - 4385 - AB76 - 5AA0280929A1 }, speed = 0
    11 - \Device\NPF_NdisWanBh, speed = 0
    12 - \Device\NPF_NdisWanIpv6, speed = 0

My Code:
        LPADAPTER lpAdapter = PacketOpenAdapter(PCHAR AdapterName);
        NetType param;
        PacketGetNetType(lpAdapter, &param);
        uint64_t speed = param.LinkSpeed;

**Comment by guyharris** [comment]
In the long run, I want to have libpcap APIs that

- enumerate interfaces, providing interface information in a form similar to what [a pcapng Interface Description Block](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii#rfc.section.4.2) provides, with options used to supply most bits of information (so that there's a way to indicate what information is available and to add new bits of information without breaking source or binary compatibility);
- provide information about a single interface, in the same form.

**Comment by dmiller-nmap** [comment]
This was fixed in e88b6f8d6e63c79a61e0c5a312e7efe7ffc460f6 (Npcap 1.30) by retrieving the link speed via GetAdaptersAddresses instead.
