### ISSUE TITLE
Faulty uninstall

### ISSUE THREAD

**Issue by Aptimex** [nmap/npcap#47]
During a recent install of Wireshark on Win10 I selected the "Restrict Npcap driver's access to Administrators only" option. However, opening Wireshark caused a bunch of repeated UAC prompts to be triggered. I can't remember the exact next sequence of events, but I eventually tried to reinstall npcap with that box unchecked. I remember the uninstall reporting success, but all attempts to reinstall with the standalone 0.9983 now fail: 
![npcap](https://user-images.githubusercontent.com/37312852/65847769-2c0c0080-e300-11e9-9992-d61d105fca9a.jpg)

I went on an npcap purge and manually deleted every reference to it that I could find:  the Program Files folder that still existed, the loopback driver in device manager, all the .dll files for it, several registry keys referencing the drivers, and probably a few other things that I can't remember. Install still fails at this screen. 

I reinstalled Wireshark several times, and each time it detects that the 0.9982 is still installed. I went so far as to look at the source code that Wireshark uses to detect whether it's already installed and found that it opens up a specific registry key. However, when I try to look that key up in RegEdit it doesn't even exist. So I have no idea why Wireshark thinks it's still installed or why the standalone installer just aborts when trying to stop the npcap driver. 

Any help would be appreciated.

**Comment by dmiller-nmap** [comment]
We did end up making improvements in the next release after this was reported (Npcap 0.9988), and even more improvements in the latest release at this time, Npcap 0.9994. If you have further problems with the Npcap installation or upgrade experience, please open a new issue. Thanks!

**Comment by FrankDudas** [comment]
I had similar problem.
Npcap blocked the internet at workplace. Thus I uninstalled it. But the uninstall got stuck. After 1 hour of waiting I restarted the computer. After this I was able to uninstall, I do not know what was the difference. But WinPcap never started again (earlier it was installed), I could not use wireshark for capturing packet (PCAP opening still worked). I tried to install the WinPcap again, but it won't work, the installer not started working because "WinPcap is already installed", but I did not find the WinPcap or Npcap in the win10settings/apps. Bad situation..... And the solution:

**digdugg suggestion worked!**
