### ISSUE TITLE
Zip build

### ISSUE THREAD

**Issue by 89z** [nmap/npcap#522]
Someone directed me here to get `wpcap.dll`:

https://nmap.org/download.html

but I noticed that no zip is available, only EXE. I think it would be helpful if a Zip was offered, so users can just extract and be done. I checked here as well with no luck:

https://github.com/nmap/npcap/releases

**Comment by fyodor** [comment]
Hi @89z.  That is a good idea, but since Npcap is a device driver running in the Windows kernel, there is a lot more to be done at install-time than just extracting the DLLs.  We need to set the service to start appropriately, install the right driver based on the Windows version and architecture, update the system certificate store so the signed driver will be allowed by Windows, etc. We do have a silent installer available for Npcap OEM (see [Internal-Use License Page](https://nmap.org/npcap/oem/internal.html) or [Redistribution License page](https://nmap.org/npcap/oem/redist.html)) and so with that you can just run with /S and be done. I hope this helps!
