### ISSUE TITLE
Npcap lwf driver has failed to be installed Error: 0x8007000d

### ISSUE THREAD

**Issue by t-node** [nmap/npcap#527]
![npcap2_git](https://user-images.githubusercontent.com/1595069/127392432-6d1a2806-2fb1-4f8c-82bc-8172fb4ee170.JPG)
![npcap3_git](https://user-images.githubusercontent.com/1595069/127392434-c3bbd88c-8c38-4b1a-98d1-b29045f1cd7e.JPG)
![npcap4_git](https://user-images.githubusercontent.com/1595069/127392436-d4f50d7d-3ba3-419d-836c-faf7de43c9f4.JPG)
![npcap1_git](https://user-images.githubusercontent.com/1595069/127392437-6400a0fb-a325-4de3-bfae-5ca69380d30c.JPG)
When ever I try to install npcap  version 1.3 with wireshark installation . I get Npcap lwf driver has failed to be installed.
I did some research into the issue but couldn't find any solution. 

I even tried to install npcap 1.5 but it also gives me similar issues.

![image](https://user-images.githubusercontent.com/1595069/127390950-415b1752-fb44-4855-9ef9-b557c1b43ed1.png)
please find attached the the install log files.

[install.log](https://github.com/nmap/npcap/files/6896259/install.log)
[NPFInstall.log](https://github.com/nmap/npcap/files/6896260/NPFInstall.log)
[DiagReport-20210728-162034.txt](https://github.com/nmap/npcap/files/6896262/DiagReport-20210728-162034.txt)

**Comment by dmiller-nmap** [comment]
Can you provide a copy of your [SetupAPI.dev.log file](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/setupapi-device-installation-log-entries)? It seems like your driver store may have become corrupted, since even our attempts to remove Npcap via pnputil are returning "Invalid data" errors. See [this similar situation](https://superuser.com/questions/759703/repair-or-rebuild-driver-store). Of course we will see if there is any further info in the SetupAPI log that may indicate a solution.

**Comment by t-node** [comment]
formatted the system to resolve the issue
