### ISSUE TITLE
After return from power save mode: "PacketReceivePacket" returns always with "ERROR_DEVICE_REMOVED"

### ISSUE THREAD

**Issue by rbeex** [nmap/npcap#542]
After Windows wakes up from power saving mode, the "PacketReceivePacket" function, that was waiting for packets before entering power saving mode, returns on each call "false" and "GetLastError" shows "ERROR_DEVICE_REMOVED (0x00000651)".
Is this Ok or an error?

**Comment by dmiller-nmap** [comment]
This is known behavior when NDIS has removed Npcap from the stack (technically: detached its filter module), even when it reattaches immediately afterwards. For all existing releases, this error is persistent and can only be cleared by closing the handle (Packet.dll `LPADAPTER` or wpcap.dll `pcap_t`) and opening a new one. For future releases, we hope that the fix for #506 will make the error transient for most cases, so that packets can be captured again from the same handle when the adapter comes back (filter module is reattached).
