### ISSUE TITLE
Injected packets not handled by IP protocol

### ISSUE THREAD

**Issue by gs-rs-21** [nmap/npcap#544]
We are porting a windows application from WinPcap to Npcap that routes packets between ethernet adapters .
The application uses pcap_open() with the flag PCAP_OPENFLAG_NOCAPTURE_LOCAL to avoid that it recaptures packets that it injects (with pcap_sendpacket()).
**With WinPcap this works for injected packets to the IP protocol (inbound) and to the wire (outbound).
With Npcap injection works only for outbound packets! The IP protocol seem not to receive the injected packets!**

Without the flag PCAP_OPENFLAG_NOCAPTURE_LOCAL packet injection works for both directions, But injected packets are captured and have to be detected and dropped.

How does Npcap decides in which direction injected packets go?

Platform is MS Server 2016 x64 and Npcap 1.55 or winpcap-nmap-4.12.

**Comment by guyharris** [comment]
`pcap_inject()` and `pcap_sendpacket()` are both defined to "inject" packets in the sense that the packet in question is sent on the interface that was opened.

They are not supposed to produce *inbound* packets seen by the network stack of the machine injecting the packets (unless it's injected on the loopback device; I'll have to see how that works on various platforms, but a case could be made that packets injected on the loopback device *should* show up as network input).

If it's useful to have such a mechanism, it should not be, by default, provided by `pcap_inject()` or `pcap_sendpacket()`.  If Npcap provides a mechanism to indicate that it should, with that mechanism *not* being the default, that's OK, but, otherwise, it breaks compatibility with other platforms.

Whether injected packets are seen by anything doing packet *capture* is another matter; I don't know whether that differs between platforms or not.

**Comment by gs-rs-21** [comment]
For me it would be the best if I could replace WinPcap with Npcap and it would behave the same way.

At now packets injected WinPcap and Npcap are seen be thy network stack on non loopback devices (at least on Windows).
The documentation of `pcap_inject()` and `pcap_sendpacket()` does not explicit define the direction of injected packets.
So it is undesirable to disable this behavior.

It would be better to explicitly define the direction of an injected packet and whether it shall be captured or not. Or there could be a capture filter to ignore injected packets.

**Comment by dmiller-nmap** [comment]
@gs-rs-21 Both WinPcap and Npcap inject packets into the Send data path. The complication arises for 2 reasons:

1. WinPcap is a NDIS 5 Protocol Driver, but Npcap is a NDIS 6 Lightweight Filter Driver, so they see traffic on the stack in different places.
2. WinPcap's documentation for the PacketSetLoopbackBehavior/PCAP_OPENFLAG_NOCAPTURE_LOCAL feature described it in terms of *what is captured* but the underlying NDIS packet handling that is changed affects *where the packet is delivered.*

The short answer is that to do what you want, you must not set PCAP_OPENFLAG_NOCAPTURE_LOCAL. Doing so prevents outbound traffic from being reflected back up the stack to protocol drivers.

**Comment by dmiller-nmap** [comment]
Longer explanation: The NDIS stack can be viewed as a pipeline, with the miniport driver at the bottom and any number of protocol drivers at the top. The miniport driver indicates received packets up the stack and sends outgoing packets that come down the stack. Filter drivers like Npcap see packets going in both directions, and can inject in either direction. Protocol drivers like WinPcap see whatever received packets they have registered for and can only inject sent packets down the stack. They also cannot ordinarily see any traffic sent by other protocol drivers. This would obviously be a problem for a packet capture driver like WinPcap.

To get around this problem, WinPcap uses a little-used feature of the NDIS stack, [loopback packets](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/looping-back-ndis-packets). By setting the `NDIS_PACKET_TYPE_ALL_LOCAL` [hardware packet filter](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-current-packet-filter), WinPcap forces NDIS to duplicate all outbound packets just before the miniport driver and send the copies back up the stack. The natural consequence of this is that WinPcap will capture the injected packet when it comes back up the stack. To get around this, they introduced the PCAP_OPENFLAG_NOCAPTURE_LOCAL behavior, which adds a NDIS 5 packet send flag, NDIS_FLAGS_DONT_LOOPBACK, to the injected packets so that they do not loop back. Now things get sketchy: I think that this flag is implemented entirely at the NDIS 5-to-6 translation, and that the packets injected into the stack do not have any such flag on them. This is because NDIS 6 takes the opposite approach: packets may be looped back under certain conditions, but the only way to *guarantee* that they are looped back is to add the NDIS_SEND_FLAGS_CHECK_FOR_LOOPBACK flag. So I believe (without a way to confirm) that PCAP_OPENFLAG_NOCAPTURE_LOCAL on Windows XP and earlier (NDIS 5-only systems) would prevent your software from working as well. But the translation of concepts from NDIS 5 to NDIS 6 in a dual-version stack makes it so that WinPcap's traffic goes where you want it to regardless of this setting.

Npcap, on the other hand, sees all outbound and inbound traffic without resorting to the performance-killing NDIS_PACKET_TYPE_ALL_LOCAL hack. We originally implemented the PCAP_OPENFLAG_NOCAPTURE_LOCAL functionality as an internal state, just sending without capturing in that case. But because this NDIS loopback data path has come to be expected by WinPcap users, we had to change that (#116). Because of the difference in loopback control concepts in NDIS 6, however, you must accept that sent packets looped back in this way will also be captured by Npcap.

There is another feature of Npcap that is useful in this regard, however. The SendToRx registry key (described in the README for [UserBridge](https://github.com/hsluoyz/UserBridge/)) causes all traffic injected on an adapter to be indicated as received data, rather than sent data. We have not officially documented this feature, though it has been present in all Npcap releases for the last 5 years. We would prefer to make this a per-handle setting, but have not prioritized extending the API to allow it to be done so.
