### ISSUE TITLE
pcap_setmode(m_PcapDescriptor, MODE_CAPT) fails

### ISSUE THREAD

**Issue by siilky** [nmap/npcap#558]
I'm using npcap in winpcap compatibility mode on windows 11.
When calling pcap_setmode(m_PcapDescriptor, MODE_CAPT) it fails on the DeviceIoControl call inside of PacketSetMode(LPADAPTER AdapterObject,int mode) function.
This seems to be a kind of regression of new releases:
in 1.55 and 1.50 builds call is failing,
1.31 works ok.

**Comment by dmiller-nmap** [comment]
Thanks for the report. Can you provide your [DiagReport](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues-diagreport) output and any info on whether other pcap functions are working for you? MODE_CAPT is the default, so unless the descriptor was in MODE_STAT previously, it shouldn't make a difference whether that function is called. (This is an implementation detail and should not be taken to mean that pcap_setmode will never need to be called in other versions, releases, or forks. I mentioned it because it may help us with debugging only.)

**Comment by siilky** [comment]
Which exactly other pcap functions are you interesting in? There are several at initialization process (I'm using that over pcap++, they have related issue for this https://github.com/seladb/PcapPlusPlus/issues/680 which I came from) like pcap_create, pcap_set_timeout, pcap_set_buffer_size, pcap_activate, pcap_datalink - they are ok.
Wireshark capture is working fine on the same setup.
Diag report is attached.
[DiagReport-20211102-183847.txt](https://github.com/nmap/npcap/files/7462546/DiagReport-20211102-183847.txt)

**Comment by dmiller-nmap** [comment]
This is a regression in Npcap 1.50 and 1.55 due to the change in f82685fa228982f7d5fa8a5416d238e4563776cc which assumed incorrectly that each `MODE_*` constant was a set bit in the mode parameter. `MODE_CAPT` is actually defined as `0`, so `pcap_setmode(p, 0)` is rejected. Since this call is effectively a no-op for capture handles that have not previously been set to `MODE_STAT`, it did not affect the software we were testing with. We will investigate better tests to avoid similar regressions in the future.

The handler for `BIOCSMODE` IoControl has been rewritten for the next release, and this bug was not reproduced. The next release of Npcap will not be affected. As a workaround, software can avoid calling `pcap_setmode` with values other than `MODE_STAT`.

**Comment by dmiller-nmap** [comment]
Fixed in Npcap 1.60.
