### ISSUE TITLE
Windows requires digitally signed driver - ERROR

### ISSUE THREAD

**Issue by kusmmat** [nmap/npcap#579]
We are using Npcap OEM 1.60
While trying to install on Windows 7 machine this error appears a few seconds after the installation is finished.
![image](https://user-images.githubusercontent.com/90252167/151271147-5d5f94d0-09c3-4127-a81c-aedb524004ce.png)
Windows 10 machines - everything's ok.

Regards Mateusz

**Comment by fyodor** [comment]
Thanks @kusmmat.  Does it work on Windows 7 if you use the /prior_driver=yes option?

**Comment by kusmmat** [comment]
> 

Yes indeed it does work without errors.

1. Is it safe to do so?
2. On WIN10 machines should we run it also with this option checked, or without (no problems on Win10 so far)?
3. What to do on WinXP machines?

**Comment by fyodor** [comment]
Hi @kusmmat.  Yes it is safe to use this.  It installs the older Npcap version 1.30 driver on older systems like this because that version was signed before a Microsoft cross-certificate used for these old Windows releases expired.  It is safe to use this on Win10+ systems as well.  They are not affected by the MIcrosoft certificate expiration problem because they use a newer MS validation system (attestation signing) which MS doesn't support on the older releases.  So the newest Npcap 1.60 driver will be installed on Win10 even with /prior_driver=yes.  So I would suggest using it in all cases where silent install is critical.

As for Windows XP, that is more than 20 years old now and MS ended extended mainstream support in 2019 and then they ceased even providing security updates or other extended support in 2014. We then waited two more years until we removed Windows XP support from Npcap in 2016.

I'm marking this issue closed, but you can still comment and let us know if you have further questions.  Also feel free to reach out to our support group if you have a maintenance plan.  Email sales at nmap.com if you need the contact info or aren't sure if you have current maintenance.  Cheers.
