### ISSUE TITLE
Distribution via Winget?

### ISSUE THREAD

**Issue by janpio** [nmap/npcap#588]
I just got a new Windows laptop and am installing all the software I need - which includes Wireshark and this project to make it really useful. Until now Winget has been a great way to install all my required tools from the command line in a scalable way - but unfortunately npcap is not available there. 

It would be great if that could be changed. 

With an installer already existing, I don't think there would be any bigger hurdles to overcome.

**Comment by dmiller-nmap** [comment]
Unattended automatic download and installation does not fit with Npcap's license and distribution requirements. A more complete discussion of this issue is in #520 .

**Comment by janpio** [comment]
Hm, that is a shame. A lot of that discussion is about hundreds of installations, but I really just want to use Winget to have a nice tool to manage the software I install on my computer (vs. downloading installers, managing updates and so on). Of course the project's decision.

**Comment by fyodor** [comment]
Thanks for the clarification @janpio.  I'm glad you brought this tool to our attention as we are always exploring the best digital distribution platforms for Npcap (and Nmap).  Winget is particularly interesting as a new (first released in mid-2020) Microsoft-developed and supported mechanism for independent software vendors to distribute their packages.  I might try it on my own Windows systems instead of the other package managers I use.

Npcap includes a system device driver, so the package manager would obviously need to support those. From some quick searching it's not completely clear whether Winget or the Windows Store can handle device drivers.  Does anyone know for sure whether it can?  Examples of drivers installed by Winget and/or using the Windows Store would be great.

Another major requirement is that Npcap or Npcap OEM distribution platforms need to either support Npcap's existing business model, or possibly an alternative/additional model.  We are only able to pay developers to improve and maintain Npcap thanks to revenue from the [Npcap OEM program](https://npcap.com/oem/).  The OEM Edition allows organizations to automate Npcap deployment with a silent installer and also gain [additional internal usage rights](https://npcap.com/oem/internal.html) (the free version license has a 5-install limit in many cases) and commercial support.  Or they can buy the [Npcap OEM redistribution license](https://npcap.com/oem/redist.html) to distribute Npcap OEM with their own software.  We don't have enough employees doing this now and our current goal is to increase revenue and hire more.

While the revenue is essential for the project to survive so it isn't abandoned like the free WinPcap and Win10Pcap projects were, our current mechanisms can impose undesirable friction on the process of downloading, installing, and keeping Npcap up to date.  And even the process of buying Npcap OEM imposes much more friction than it should on both the customers and us (the Nmap Project).  I spend hours every day dealing with sending quotes, purchase orders, invoices, creating customer accounts and license certificates, vendor onboarding,  contract negotiation, accounting, taxes, renewals, etc.  It also makes the purchase process take days (usually) when payment and delivery could and should be immediate.  So a better digital distribution system could benefit everyone involved.

The purchase process is involved enough that we don't have any middle ground between the free Npcap license and the 100-seat Npcap OEM license costing US$2,900.  In an ideal world, a user like you could maybe pay a small amount to have your own single-user license of Npcap OEM which can be installed and kept up to date using package management systems that are convenient for you.  All in a few clicks (or a simple command line invocation).  This isn't revolutionary.  It's what we're used to with app stores on our phone already.  Npcap is just so new that we haven't found and implemented a good fit yet.  It's high on our priority list though, and we welcome all suggestions.

Our current near-term plan is to build an online "Npcap store" where people can go to buy Npcap licenses for immediate payment and delivery.  But a system like Winget could be even better if we can find one which meets our needs.  It could make delivery and payment seamless just like the store, but also add in the software installation, management, and automatic updates if desired.  It could also help with tracking the number of users/installs so customers could only pay for what they need.  Right now we offer just the 100, 500, and unlimited options besides the free/demo version.

Getting back to Winget itself, the problematic limitations I see are:
- It's not clear to me whether it can even support system device drivers such as Npcap or is only for User mode applications.
- It's not clear to me whether it can support payment for apps like Npcap OEM.  Microsoft mentions a Windows Store integration but that may only be for free apps and I'm not sure the Windows Store supports drivers either.
- Can it handle any sort of usage counting?  If we put the free/demo version of Npcap on there, we might want to limit it to a small number of installs to avoid companies inadvertently bypassing the 5-install limit in its license agreement.  Note that the 5-install limit doesn't apply to usage solely with Nmap or Wireshark.  If they handle payment, we could potentially put Npcap OEM on there and usage counting would help us charge just a small amount for companies and individuals only using a small number of copies while charging more for those deploying Npcap OEM across huge enterprises.

I'll re-open this ticket since I am interested in the discussion and would be happy to hear suggestions on how to implement these goals with Winget or other software.  I'd also be happy to hear about any other drivers and/or paid software using winget or other popular package managers that we could sort of use as a model. Since this is a broader issue than just Winget, I'll probably open a new broader ticket as well.

**Comment by janpio** [comment]
Thanks for the additional insight.

I just learned that the licence even has a special case for Wireshark, which is how I learned about Npcap - so I am even a user that only wants to install on 1 machine, to use for a use case where doing more would not even be a problem for the licence 😆 🤷 

As far as I know Winget can run _any_ self contained installer. Sometimes I have to approve installations (for permissions reasons). What these installers do is totally up to them. Creating a package for Winget also seems to be pretty simple: You just need public URLs for your installers and then create a few yaml files (manifests), validate these and then commit them to a public GitHub repository. Here is an example for Notepad++: https://github.com/microsoft/winget-pkgs/tree/2264d2753c184a3872f7fc098a6db5f2deca038a/manifests/n/Notepad%2B%2B/Notepad%2B%2B/8.3.3 As you already have the installer, it might be as simple as creating the automation to create and update the yaml files and submit the PRs (both of which is automatable via e.g. GH Actions.)

I don't think Winget has any commercial model or approaches behind it - it really is "just" a package manager where you say which package you want, it checks if it knows about that and then downloads and installs it. It does not do anything App Store like at all. (The Microsoft Store would be the MS equivalent to that, and although you can also install apps from that via Winget, I completely avoid it.)

From your description a way forward could be to only offer `Npcap Free Edition` via Winget. For users like me (1 computer, Wireshark user), that would be pretty much the same as going to https://npcap.com/, not reading much and just clicking the first link that mentions `installer` under the `Download` headline (At least that is my usual process...) and then run that. Just much cleaner via `winget install`.

**Comment by aetonsi** [comment]
I looked up npcap because i randomly saw it in the list of installed software on my notebook (can't remember why i have it.. fiddler? wireshark? snort? i use them all occasionally).
Anyway i saw that a newer version was available for download, so i instinctively, immediately, ran:
```powershell
winget upgrade npcap
choco upgrade npcap
scoop update npcap
```
and then i was like **:((**

In all seriousness, concerning your 3 points, @fyodor:
1. Even if it requires a graphical installation, user confirmation, administrator privileges, reboot, etc, i think it could be done :)
Via choco and winget you can install Virtualbox, which requires kernel drivers and/or reboot, if i remember correctly.
On scoop, since it's meant to be used for "user scoped", locally installed apps, i don't think it would be possible at all.
2. I don't know anything about possible payments integrations for the OEM version, sorry.
But it would be really cool if at least the _free_ version was available via one of these channels.
[ also, i mean, if there's a will, there's a way.. nothing's stopping people from creating a simple script that fetches the latest available build, downloads it, builds it, and starts the installation; or even simpler, a script that fetches the website's source, parses it and extrapolates the link to download the ready-to-go installer ]
3. I know nothing at all about usage counting, for the OEM version, sorry.
But surely, choco and winget and whatever can provide stats about downloads, for this _hypothetical_ **free** version..
Also, choco installations are just powershell scripts, that usually download right from the software's original website, so you could track downloads on your website's server-side scripts, if that's how you (possibly) already monitor for license infringements (like more than 5 downloads from the same IP). I don't know.

have a nice day

PS: also apparently npcap already _was_ on choco? https://community.chocolatey.org/packages/npcap

**Comment by fyodor** [comment]
For what it is worth, we've worked with the [PatchMyPC](https://patchmypc.com/) folks to support Npcap OEM for automated deployment.  They don't have a "store" to handle payment, so you still need to [buy Npcap OEM the normal way](https://npcap.com/oem/internal.html) and then you upload the installer binary to a private repo using their system.  And they track new Npcap releases so they can tell you when yours needs updating.

But in your case, if it's just for your one notebook computer, it may be easier (and certainly would be cheaper) to just download the free/demo version of Npcap and install that in a few clicks.

I'm closing this issue because it's more of a discussion than something actionable and I don't want to clog the issue tracker with those. People can still leave comments on "closed" issues and we always welcome your ideas.

**Comment by aetonsi** [comment]
Yeah you're right thanks for making me notice i turned it into a discussion. So should we continue here in the comments or in a new discussion? 
(i don't see where to open a discussion, so i'll go on down here, and if there will be a separate discussion, i'll cut+paste my comment there)

---

Yes, for sure installing npcap is just a few clicks, i don't deny that.
It's only that, even a few clicks+waiting for download+opening the installer+UAC prompt+installing+closing the installer, multiplied for even just ~15/20 apps (which is more or less the number of updates i get weekly, running my update script), becomes a _pain_ and takes about 30-45 minutes (mostly download time) and constant interruptions, for each installation. 

Things like `winget` and `choco` take that _pain_ away, mostly, thanks to silent installs.
But as i think i said it would be perfectly fine even to have a GUI install for `npcap`: since just a few of the apps installed via package managers have graphical installations (i remember for example Visual Studio Community), it's still way better than having to stop for each of the ~15 installs.

But having to ***remember*** which apps are not installable via **_any_** package manager, now _**that**_ becomes tedious...

PS: if you think ~15/20 apps updating each week seems a lot, it's not, if you have installed 150+ apps via choco.. (not counting the `winget`-only apps because i don't have the time to filter out the ones i install via `choco` already)

**Comment by bt4ibwem8** [comment]
@fyodor 
It would be nice if you allow open-source project `Scoop` to add npcap with silent install. Maybe if you provide them oem licence or some other way...

**Comment by zumm** [comment]
So now, 3 years later, you guys still gatekeeping win ecosystem from evolving? With excuses like "ppl won't read our license if they use package manager"?

**Comment by shodanx2** [comment]
Hello,

I made a script that fully automated the installation of the normal version of npcap.

Save the script below as "install npcap.bat" and run as admin.
It will download npcap and then install it.

Here is a video demontration of it in action

https://github.com/user-attachments/assets/66542b50-023a-44a6-b7bd-17a8742da47c

```
@echo off
:setup
call :clear_target_vars & call :npcap_set_ESC_variable
if not defined applist.ubound call :create_applist "npcap" "latest" "hashmissing" "sha256" "npcap-1.85.exe" "https://npcap.com/dist/npcap-1.85.exe"
set "target.pid="
set "target.app=npcap"
set "VERBOSE=true"
set "DEBUG=true"
set "DEBUG=" & REM set "DEBUG=true"
set "target.installer="
call :search_applist %target.app% DownloadAppList_index
if exist "latest\npcap-latest.exe" ( set "target.installer=latest\npcap-latest.exe" ) else if exist "%%applist[%DownloadAppList_index%].filename%%" ( call set "target.installer=%%applist[%DownloadAppList_index%].filename%%" ) else if exist "installers\%%applist[%DownloadAppList_index%].filename%%" ( call set "target.installer=installers\%%applist[%DownloadAppList_index%].filename%%" )
if not defined target.installer ( call :download "%%applist[%DownloadAppList_index%].filename%%" "%%applist[%DownloadAppList_index%].url%%" & call set "target.installer=%%applist[%DownloadAppList_index%].filename%%") 
:main

( if /i "[%DEBUG%]" EQU "[true]" echo start /b "" "%target.installer%" ) & start /b "" "%target.installer%" & timeout /t 2 >nul

( if /i "[%DEBUG%]" EQU "[true]" echo call :get_install_pid ) & call :get_install_pid

( if /i "[%DEBUG%]" EQU "[true]" echo call :find_button "I &Agree" ) & call :find_button "I &Agree"
( if /i "[%DEBUG%]" EQU "[true]" echo call :push_button ) & call :push_button

( if /i "[%DEBUG%]" EQU "[true]" echo call :center_and_focus_window ) & call :center_and_focus_window

( if /i "[%DEBUG%]" EQU "[true]" echo call :find_button_exact "Install" ) & call :find_button_exact "&Install"
( if /i "[%DEBUG%]" EQU "[true]" echo call :get_button_coordinates ) & call :get_button_coordinates
( if /i "[%DEBUG%]" EQU "[true]" echo call :click_button ) & call :click_button

( if /i "[%DEBUG%]" EQU "[true]" echo call :center_and_focus_window ) & call :center_and_focus_window

( if /i "[%DEBUG%]" EQU "[true]" echo call :find_button "next" ) & call :find_button "next"
( if /i "[%DEBUG%]" EQU "[true]" echo call :waiting_for_install ) & timeout /t 3 >nul & call :waiting_for_install
( if /i "[%DEBUG%]" EQU "[true]" echo call :push_button ) & call :push_button

( if /i "[%DEBUG%]" EQU "[true]" echo call :find_button_exact "Finish" ) & call :find_button_exact "Finish"
( if /i "[%DEBUG%]" EQU "[true]" echo call :get_button_coordinates ) & call :get_button_coordinates
( if /i "[%DEBUG%]" EQU "[true]" echo call :click_button ) & call :click_button

:end
GoTo :EOF

:npcap_get_installer_pid (input) target.app (output) target.pid
for /f "usebackq tokens=*" %%A in (`powershell -command "$targetApp = [Environment]::GetEnvironmentVariable('target.app'); Get-Process | Where-Object { $_.Name -match $targetApp } | ForEach-Object { $_.Id }"`) do set "target.pid=%%A"
if "[%target.pid%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_get_button_hwnd_exact
set "target.search.exact.mode=true" & GoTo :npcap_get_button_hwnd_internal
:npcap_get_button_hwnd (input) target.pid target.text
set "target.search.exact.mode="
:npcap_get_button_hwnd_internal
for /f "usebackq tokens=*" %%A in (`powershell -command "$global:targetPid = [int][Environment]::GetEnvironmentVariable('target.pid'); $global:targetText = [Environment]::GetEnvironmentVariable('target.text'); $global:out = New-Object System.Collections.Generic.List[string]; $code = 'using System; using System.Text; using System.Runtime.InteropServices; public class Win32 { public delegate bool EnumWindowsProc(System.IntPtr hWnd, System.IntPtr lParam); public delegate bool EnumChildProc(System.IntPtr hWnd, System.IntPtr lParam); [DllImport(\"user32.dll\")] public static extern bool EnumWindows(EnumWindowsProc lpEnumFunc, System.IntPtr lParam); [DllImport(\"user32.dll\")] public static extern bool EnumChildWindows(System.IntPtr hWndParent, EnumChildProc lpEnumFunc, System.IntPtr lParam); [DllImport(\"user32.dll\")] public static extern int GetWindowText(System.IntPtr hWnd, StringBuilder lpString, int nMaxCount); [DllImport(\"user32.dll\")] public static extern int GetDlgCtrlID(System.IntPtr hWnd); [DllImport(\"user32.dll\")] public static extern uint GetWindowThreadProcessId(System.IntPtr hWnd, out uint lpdwProcessId); }'; Add-Type -TypeDefinition $code; [void][Win32]::EnumWindows([Win32+EnumWindowsProc]{ param($hWnd, $lParam) [void][Win32]::EnumChildWindows($hWnd, [Win32+EnumChildProc]{ param($chWnd, $lp) $sb = New-Object System.Text.StringBuilder 512; [void][Win32]::GetWindowText($chWnd, $sb, 512); $ctrlId = [Win32]::GetDlgCtrlID($chWnd); $procId = 0; [void][Win32]::GetWindowThreadProcessId($chWnd, [ref]$procId); $ctrlText = $sb.ToString().Replace([Environment]::NewLine,' '); if ($procId -eq $global:targetPid) { if ([Environment]::GetEnvironmentVariable('target.search.exact.mode') -eq 'true') { if ($ctrlText -eq $global:targetText) { $global:out.Add($chWnd) } } else { if ($ctrlText -like ('*' + $global:targetText + '*')) { $global:out.Add($chWnd) } } }; $true }, [intptr]::Zero); $true }, [intptr]::Zero); $global:out"`) do set "target.hwnd=%%A"
if "[%target.hwnd%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_get_window_hwnd (input) target.hwnd (output) target.tophwnd
for /f "usebackq tokens=*" %%A in (`powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class Win32 { [DllImport(\"user32.dll\")] public static extern IntPtr GetAncestor(IntPtr hWnd, uint gaFlags); }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.hwnd'); $GA_ROOT = 2; $topHwnd = [Win32]::GetAncestor($hwnd, $GA_ROOT); Write-Output $topHwnd"`) do set "target.tophwnd=%%A"
if "[%target.tophwnd%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_center_window (input) target.tophwnd
powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class Win32 { [DllImport(\"user32.dll\")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect); [DllImport(\"user32.dll\")] public static extern bool MoveWindow(IntPtr hWnd, int X, int Y, int nWidth, int nHeight, bool bRepaint); [DllImport(\"user32.dll\")] public static extern int GetSystemMetrics(int nIndex); [StructLayout(LayoutKind.Sequential)] public struct RECT { public int Left, Top, Right, Bottom; } }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.tophwnd'); $rect = New-Object Win32+RECT; if ([Win32]::GetWindowRect($hwnd, [ref]$rect)) { $w = $rect.Right - $rect.Left; $h = $rect.Bottom - $rect.Top; $sw = [Win32]::GetSystemMetrics(0); $sh = [Win32]::GetSystemMetrics(1); $x = [math]::Max(0, ($sw - $w) / 2); $y = [math]::Max(0, ($sh - $h) / 2); [Win32]::MoveWindow($hwnd, $x, $y, $w, $h, $true) }" >nul
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_alwaysontop_window (input) target.tophwnd
powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class Win32 { public static readonly IntPtr HWND_TOPMOST = new IntPtr(-1); public static readonly IntPtr HWND_NOTOPMOST = new IntPtr(-2); public const uint SWP_NOMOVE = 0x0002, SWP_NOSIZE = 0x0001, SWP_SHOWWINDOW = 0x0040; [DllImport(\"user32.dll\")] public static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int X, int Y, int cx, int cy, uint uFlags); }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.tophwnd'); [Win32]::SetWindowPos($hwnd, [Win32]::HWND_TOPMOST, 0, 0, 0, 0, [Win32]::SWP_NOMOVE -bor [Win32]::SWP_NOSIZE -bor [Win32]::SWP_SHOWWINDOW)" >nul
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_foreground_window (input) target.tophwnd
powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class Win32 { [DllImport(\"user32.dll\")] public static extern bool SetForegroundWindow(IntPtr hWnd); }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.tophwnd'); [Win32]::SetForegroundWindow($hwnd)" >nul
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_push_button (input) target.hwnd
powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class Win32 { [DllImport(\"user32.dll\")] public static extern bool PostMessage(IntPtr hWnd, UInt32 Msg, IntPtr wParam, IntPtr lParam); }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.hwnd'); [Win32]::PostMessage($hwnd, 0x00F5, [intptr]0, [intptr]0)" >nul
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_get_button_coordinates (input) target.hwnd
for /f "usebackq tokens=1,2" %%A in (`powershell -command "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public struct RECT { public int Left, Top, Right, Bottom; } public class Win32 { [DllImport(\"user32.dll\")] public static extern bool GetWindowRect(System.IntPtr hWnd, out RECT lpRect); }'; $hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.hwnd'); $rect = New-Object RECT; if ([Win32]::GetWindowRect($hwnd, [ref]$rect)) { $left = $rect.Left + 5; $top = $rect.Top + 5; $right = $rect.Right - 5; $bottom = $rect.Bottom - 5; if ($right -le $left -or $bottom -le $top) { exit 3 }; $rand = New-Object System.Random; $x = $rand.Next($left, $right); $y = $rand.Next($top, $bottom); \"$x $y\" } else { exit 1 }"`) do set "target.x=%%A" & set "target.y=%%B"
if "[%target.x%]" NEQ "[]" ( if "[%target.x%]" NEQ "[]" ( exit /b 0) else ( exit /b 1 ) ) else ( exit /b 1 )

:npcap_click_coordinates (input) target.x target.y
powershell -command "Add-Type -AssemblyName System.Windows.Forms; Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class MouseSim { [DllImport(\"user32.dll\")] public static extern bool SetCursorPos(int X, int Y); [DllImport(\"user32.dll\")] public static extern void mouse_event(uint dwFlags, int dx, int dy, uint dwData, UIntPtr dwExtraInfo); public const uint MOUSEEVENTF_LEFTDOWN = 0x02; public const uint MOUSEEVENTF_LEFTUP = 0x04; }'; $x = [int][Environment]::GetEnvironmentVariable('target.x'); $y = [int][Environment]::GetEnvironmentVariable('target.y'); [MouseSim]::SetCursorPos($x, $y); Start-Sleep -Milliseconds 50; [MouseSim]::mouse_event([MouseSim]::MOUSEEVENTF_LEFTDOWN, $x, $y, 0, [UIntPtr]::Zero); Start-Sleep -Milliseconds 50; [MouseSim]::mouse_event([MouseSim]::MOUSEEVENTF_LEFTUP, $x, $y, 0, [UIntPtr]::Zero)" >nul
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:npcap_wait_until_button_not_disabled (input) target.hwnd target.waittimeout
powershell -command "$hwnd = [intptr][int][Environment]::GetEnvironmentVariable('target.hwnd'); $envTimeout = [Environment]::GetEnvironmentVariable('target.waittimeout'); $timeoutSec = 300; if ($envTimeout -match '^\d+$') { $timeoutSec = [int]$envTimeout }; $code = 'using System; using System.Runtime.InteropServices; public class Win32 { [DllImport(\"user32.dll\")] public static extern bool IsWindowEnabled(IntPtr hWnd); }'; Add-Type -TypeDefinition $code; $deadline = [datetime]::Now.AddSeconds($timeoutSec); while (-not [Win32]::IsWindowEnabled($hwnd)) { if ([datetime]::Now -ge $deadline) { exit 1 }; Start-Sleep -Milliseconds 500 }; exit 0"
if "[%errorlevel%]" NEQ "[]" ( exit /b 0 ) else ( exit /b 1 )

:center_and_focus_window
call :npcap_get_window_hwnd 
if not errorlevel 1 ( if /i "[%VERBOSE%]" EQU "[true]" ( echo %ESC%[32mFound handle%ESC%[0m of "%target.text%"'s button's top window "%ESC%[32m%target.tophwnd%%ESC%[0m" ) ) else ( if /i "[%VERBOSE%]" EQU "[true]" ( echo could not handle of top window ) )
call :npcap_foreground_window
if /i "[%VERBOSE%]" EQU "[true]" ( <nul set /p=Top window hWnd %ESC%[32m%target.tophWnd%%ESC%[0m made... %ESC%[32mforegrounded%ESC%[0m... )
call :npcap_center_window
if /i "[%VERBOSE%]" EQU "[true]" ( <nul set /p= %ESC%[32mcentered%ESC%[0m... )
call :npcap_alwaysontop_window
if /i "[%VERBOSE%]" EQU "[true]" ( echo %ESC%[32malways on top%ESC%[0m )
exit /b 0

:get_install_pid (input) target.app (output) target.pid
set /a loop_count=0 >nul
:get_install_pid_loop
call :npcap_get_installer_pid 
if not errorlevel 1 ( if /i "[%VERBOSE%]" EQU "[true]" ( echo %ESC%[32mFound%ESC%[0m PID of "%target.app%", "%ESC%[32m%target.pid%%ESC%[0m" ) & exit /b 0 ) else ( if /i "[%VERBOSE%]" EQU "[true]" ( echo %ESC%[31mCould not find PID%ESC%[0m of %target.app%... ) & set /a loop_count=+1 >nul & timeout /t 3 & if %loop_count% GEQ 10 ( echo Timeout exceeded,%ESC%[31m exiting%ESC%[0m & exit /b 1 ) else ( GoTo :get_install_pid_loop ) )

:find_button_exact (input) target.text or first argument
set "find_button_exact=true" & GoTo :find_button_internal
:find_button (input) target.text or first argument
set "find_button_exact="
:find_button_internal
if "[%~1]" NEQ "[]" set "target.text=%~1"
set /a loop_count=0 >nul
:find_button_loop
if "[%find_button_exact%]" EQU "[true]" ( call :npcap_get_button_hwnd_exact ) else ( call :npcap_get_button_hwnd )
if not errorlevel 1 ( if /i "[%VERBOSE%]" EQU "[true]" ( echo Found hWnd of "%ESC%[32m%target.text%%ESC%[0m" button, %ESC%[32m%target.hwnd%%ESC%[0m ) & exit /b 0 ) else ( if /i "[%VERBOSE%]" EQU "[true]" ( echo %ESC%[31mCould not find%ESC%[0m hWnd of button containing "%target.text%" in PID %target.pid%... ) & set /a loop_count=+1 >nul & timeout /t 3 & if %loop_count% GEQ 10 ( echo Timeout exceeded,%ESC%[31m exiting%ESC%[0m & exit /b 1 ) & GoTo :find_button_loop )

:push_button
if /i "[%VERBOSE%]" EQU "[true]" ( <nul set /p=Pushing button "%ESC%[32m%target.text%%ESC%[0m" with hWnd %ESC%[32m%target.hWnd%%ESC%[0m... )
call :npcap_push_button
if /i "[%VERBOSE%]" EQU "[true]" ( echo button has been %ESC%[32mpushed%ESC%[0m )
exit /b 0

:get_button_coordinates
if /i "[%VERBOSE%]" EQU "[true]" echo Obtaining X,Y coordinates inside "%ESC%[32m%target.text%%ESC%[0m" button 
call :npcap_get_button_coordinates
if /i "[%VERBOSE%]" EQU "[true]" echo Found location X and Y inside button "%target.text%",%target.hwnd%,%ESC%[32m%target.x%,%target.y%%ESC%[0m
exit /b 0 

:click_button
if /i "[%VERBOSE%]" EQU "[true]" ( <nul set /p=Clicking button "%target.text%" with hWnd %target.hWnd%, coordinates %ESC%[32m%target.x%,%target.y%%ESC%[0m )
call :npcap_click_coordinates
if /i "[%VERBOSE%]" EQU "[true]" ( echo has been %ESC%[32mclicked%ESC%[0m )
exit /b 0

:waiting_for_install
if /i "[%VERBOSE%]" EQU "[true]" echo %ESC%[32mWaiting%ESC%[0m until end of installation
call :npcap_wait_until_button_not_disabled
if /i "[%VERBOSE%]" EQU "[true]" echo Installation %ESC%[32mcompleted%ESC%[0m
exit /b 0

:npcap_set_ESC_variable
for /f %%a in ('echo prompt $E^| cmd') do (set "ESC=%%a")
exit /b 0

:create_applist
:: Usage: call :create_applist "name" "version" "hash" "hashtype" "filename" "url"
:: Check if index is initialized
if defined applist.ubound ( set /a applist.ubound+=1 ) else ( set "applist.ubound=0" )
:: Store fields in indexed variables
set "applist[%applist.ubound%].name=%~1"
set "applist[%applist.ubound%].version=%~2"
set "applist[%applist.ubound%].hash=%~3"
set "applist[%applist.ubound%].hashtype=%~4"
set "applist[%applist.ubound%].filename=%~5"
set "applist[%applist.ubound%].url=%~6"
set "applist[%applist.ubound%].urlreferer=%~7"
set "applist[%applist.ubound%].postdownload=%~8"
set "applist[%applist.ubound%].dependencies=%~9"
goto :EOF

:GetExtension
rem %1 = filename, %2 = output var name
for %%F in ("%~1") do set "%2=%%~xF"
call set "%2=%%%2:~1%%"
exit /b

REM === Function to download a file ===
:download
REM %1 = filename, %2 = URL
echo Downloading %2 to %1 ...
curl -L -o "%~1" "%~2"
if %errorlevel% neq 0 (
    echo Error: %ESC%[31mFailed%ESC%[0m to download %~2
    exit /b 1
)
exit /b

REM === Function to create a hardlink ===
:hardlink
REM %1 = sourcefile, %2 = hardlinkfile
REM Check if the target already exists
if exist %~2 del /f /q "%~2"
for /f "delims=" %%A in ('mklink /H "%~2" "%~1" 2^>^&1') do (
    if "[%%A]"=="[The process cannot access the file because it is being used by another process.]" goto :hardlink
	echo %%A
)
exit /b


:GetFileHash
:: Usage: call :GetFileHash "file.exe" returnVar [hashtype]
set "hashtype=%~3"
if not defined hashtype set "hashtype=SHA256"
for /f "tokens=1" %%H in (
    'certutil -hashfile "%~1" %hashtype% ^| find /i /v "hash" ^| findstr /r "[0-9A-Fa-f]"'
) do ( call set "%~2=%%H" & exit /b 0 )
echo Error: Could not get hash for %~1
exit /b 1

:clear_target_vars
for %%V in (hwnd tophwnd x y text) do set "target.%%V="
exit /b

:search_applist
if not defined applist.ubound ( set "%2=" & goto :EOF )
setlocal EnableDelayedExpansion
for /L %%A in (0,1,%applist.ubound%) do (
    set /i "temp_var=!applist[%%A].name!"
    set "match_check=!temp_var:%~1=!"
    if not "!match_check!"=="!temp_var!" ( endlocal & set "%2=%%A" & goto :EOF )
)
set "%2="
goto :EOF
```

That was 3 whole days of work !!

**Comment by ShortArrow** [comment]
I'm trying to better understand the concern around Winget distribution.

Since the free version doesn't support silent installation, my understanding is that a Winget package for the free installer would still launch the normal interactive installer rather than enable unattended deployment.

If that's correct, could you help me understand how such a package would conflict with the current business model?
