### ISSUE TITLE
Accept license via command line [License screen showing up]

### ISSUE THREAD

**Issue by dreagor** [nmap/npcap#589]
Hi

in my work, we need to install npcap-1.55-oem.exe in several servers and want to automate the process, we have already the installer but if I try to install it via command line I don't find the option to accceptEULA or similar in the documentation

in powershell i do something like:

`.\npcap-1.55-eom.exe /s `

but the license screen still showing up. could you please help me? other options should be the default so i think that should be enough, right?

https://npcap.com/guide/npcap-users-guide.html

**Comment by fyodor** [comment]
Hi @dreagor.  The /S option (note the capitalization) enables silent installation with Npcap OEM.  Please note that using Npcap OEM requires a license from us (Nmap Software LLC) or in some cases you can get it from 3rd party OEMs for Npcap OEM use with their software.  We've posted [prices and details for purchasing Npcap OEM internal-use licenses here](https://npcap.com/oem/internal.html).  Contact sales@nmap.com with any questions. Also we recommend using the latest version, which is 1.60.  You can read about the improvements made since Version 1.55 [in the changelog](https://npcap.com/changelog). Cheers!

**Comment by Nandhu0528** [comment]
1. Hi Fyodor, We do have a licensed one, which comes with one of our bundled application. So we tried to install that one using powershell script to multiple servers. So we are finding an option to install in multiple servers.

**Comment by fyodor** [comment]
Hi @dreagor and @Nandhu0528.  I think the issue here is that Npcap OEM is being called with /s (lowercase) while the silent option is actually /S (uppercase).  We are hoping to make Npcap and Nmap installer options case-insensitive in a future release to avoid this issue.  But for now, use /S rather than /s for silent install.  Please note that the silent install option is only available with [Npcap OEM](https://npcap.com/oem/), not the free/demo version of Npcap.
