### ISSUE TITLE
Npcap: pcap_findalldevs is very slow

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#61]
Users are complaining about Wireshark taking a long time to populate the list of adapters, even going so far as to suggest turning off Npcap when using Wireshark for reading pcap files. This shouldn't take so long.

The most promising idea so far is: Don't try to open each adapter as it is found (PacketOpenAdapter) in order to determine if it is supported. Packet API docs (unpublished) indicate that PacketGetAdapterNames is supposed to only return supported adapters, but I don't know if anything relies on that. Need to check libpcap to see, since that's the primary consumer of that API.

**Comment by guyharris** [comment]
In libpcap, `pcap_findalldevs()` calls `pcap_platform_finddevs()` to find all the regular interfaces (as well as calling the "find devices" routines for various pcap "modules", if configured in), and the NPF version (in pcap-npf.c) calls `PacketGetAdapterNames()` twice - once to get the size of the adapter list so that it can allocate a buffer for the list, and once to read the list into the buffer.

`PacketGetAdapterNames()` calls `PacketPopulateAdaptersInfoList()`.  `PacketPopulateAdaptersInfoList()` always empties out the current list and then calls, in order:

- `PacketGetAdaptersNPF()`;
- `PacketGetAdaptersIPH()`;
- `PacketAddAdapterNPF()` to add the loopback adapter, if loopback support is configured in.;
- `PacketGetAdaptersAirpcap()`, if the AirPcap DLL is loaded;
- `PacketGetAdaptersDag()`, if the Endace DAG card support is available;

to fill in the list.

`PacketGetAdaptersNPF()` digs through the Registry to find adapters; for each adapter it finds, it calls `PacketAddAdapterNPF()`.

`PacketAddAdapterNPF()` first iterates over the list to see if it's already been added, and just returns if it has.  Otherwise, it attempts to open the adapter, using `PacketOpenAdapterNPF()` and, if that succeeds, adds it.  (I've omitted some details such as the `INFO_FLAG_DONT_EXPORT` flag.)

`PacketAddAdapterNPF()` tries to find the IPv4 and IPv6 addresses for the adapter.

To find the IPv4 addresses, it calls `PacketGetAddressesFromRegistry()`.  `PacketGetAddressesFromRegistry()` calls `IsIPv4Enabled()`, which calls...

...`GetAdaptersAddresses()`.

To get all the IPv6 addresses for the adapter, it calls `PacketAddIP6Addresses()`.

`PacketAddIP6Addresses()` gets the adapter's IPv6 addresses by...

...calling `GetAdaptersAddresses()`, looking for the adapter in the list, and getting the IPv6 addresses from that list.

So we end up calling `GetAdaptersAddresses()` in this process.  We end up calling it *twice per interface* in this process.

Oh, and then `pcap_platform_finddevs()`() calls `packet_add_if_npf()` per interface; that then calls `PacketGetNetInfoEx()`, which again calls `PacketGetAddressesFromRegistry()` and `PacketAddIP6Addresses()`, so there are even *more* per-adapter `GetAdaptersAddresses()` calls.

`PacketGetAdaptersIPH()` calls `GetAdaptersInfo()`, which, as @akontsevoy notes in [this comment on issue 26](https://github.com/nmap/npcap/issues/26#issuecomment-631267268), is probably a wrapper for `GetAdaptersAddresses()` since Windows XP.  I'm not sure we need `PacketGetAdaptersIPH()` *and* `PacketGetAdaptersNPF()`, unless there are Npcap-usable adapters that `PacketGetAdaptersIPH()` would find but `PacketGetAdaptersNPF()` wouldn't find *and* Npcap-usable adapters that `PacketGetAdaptersNPF()` would find but `PacketGetAdaptersIPH()` would find.

This code needs some work.  I have a version of libpcap's pcap-npf.c where `pcap_platform_finddevs()` calls `GetAdaptersAddresses()` directly and iterates once through the list it provides.  Unfortunately, it currently has to call `PacketOpenAdapter()` to check whether the interface is supported by Npcap, and that ends up calling `PacketFindAdInfo()`, which ends up calling `PacketPopulateAdaptersInfoList()` if the list is empty.  That's used to determine whether the device is a regular NPF device, a DAG device, or an AirPcap device.

The current master branch of libpcap includes direct support for AirPcap devices (tested on a Windows VM; it works).  If we were to remove the AirPcap support from Npcap, and leave that up to libpcap, that would leave only the DAG devices.  [Endace currently doesn't support Windows, only Linux and FreeBSD](https://www.endace.com/endace-high-speed-packet-capture-solutions/oem/dag/), and libpcap already has DAG support, so that might be another case to leave up to libpcap; were Endace to support Windows again, they'll probably either contribute whatever changes are needed to pcap-dag.c or I'd nag them into doing so. :-)

So the first question is whether, were packet.dll not to provide `PacketGetAdapterNames()` at all, the list of adapters would be necessary.

If not, it could be removed, and `PacketOpenAdapter()` could just try opening the device through the driver, with the new pcap-npf.c used; that would probably be significantly faster (the profiling I did with a test program that repeatedly called `pcap_findalldevs()` found a *lot* of the time in `pcap_findalldevs() is spent in repeated calls to `GetAdaptersAddresses()`).

If it *is* necessary, perhaps it could just be a list of names, not full interface information.

Alternatively, a `PacketGetAdapterInfo()` routine could be provided, which just hands back a buffer full of `IP_ADAPTER_ADDRESSES` structures fetched from a single `GetAdaptersAddresses()` call.  It could allocate a buffer large enough for all the adapters found by `GetAdaptersAddresses()` *plus* an extra entry, added at the beginning, for the loopback device, if present.  In addition, it could adjust the "next interface" pointers so that the list in that buffer doesn't include interfaces not supported by Npcap.  It would return both a pointer to the raw buffer, for the caller to hand to a packet.dll routine to free, and a pointer to the first interface supported by Npcap.  That would let the caller decide what information it wants; some of the information in the `IP_ADAPTER_ADDRESSES` structure wouldn't be useful to `pcap_findalldevs()`, but might be useful to future libpcap APIs that would return more information (e.g., many of the options in [a pcapng Interface Description Block](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii#rfc.section.4.2)).
