### ISSUE TITLE
Is Windows Embedded Standard supported by Npcap?

### ISSUE THREAD

**Issue by guyharris** [nmap/npcap#637]
In [this StackOverflow question](https://stackoverflow.com/questions/73619011/npcap-async-sniffer?noredirect=1#comment130357131_73619011), the person asking the question claims that "on this PC the installed windows is not compatible with Npcap".

They later indicated that the OS in question is "windows embedded standard 7 with sp1".

As far as I know, Windows Embedded Standard 7 is an embedded version of Windows 7.  Npcap currently supports Windows 7; does it also support Windows Embedded Standard 7?

**Comment by fyodor** [comment]
Hi @guyharris! Thanks for relaying this. Npcap ought to still work with Windows 7 as we do still install that ancient driver with it.  And we have not dropped all support for Windows 7 since there are certain versions (including Embedded Standard 7) which are still eligible for special paid support by MS.  But most Windows 7 versions are completely EOL by Microsoft.  So if the user is having a problem with Npcap on Windows Embedded Standard 7, they are welcome to open an issue here with full details.  If they are an Npcap OEM customer with a support contract then they should contact us using their support contracts in their license certificate or at least mention in the issue here that they are customers and what company they are with.  Unfortunately we aren't able to devote many free support resources to dead-end platforms like Windows 7  But we'd at least take a look at any issue filed in case the solution is obvious.  Or maybe some other Windows Embedded Standard 7 user might have advice for them.  They could consider trying older Npcap releases as well.
