### ISSUE TITLE
Npcap | Receiving back packets sent to a network interface

### ISSUE THREAD

**Issue by farcas-snps** [nmap/npcap#648]
**Describe the bug**
My app continuously writes and reads packets from a network interface. The problem is that it receives back packets just sent. Promiscuous mode does not influence the outcome and _pcap_setdirection_ is not supported on my device.
On Linux, this does not happen when using libpcap.

**To Reproduce**
1. Write a packet (pcap_sendpacket) to **any** network interface.
2. Read available packets from the same interface (pcap_next_ex).
3. Packet sent at 1. is received back...

**Expected behavior**
I expect **not to** receive back packets sent by myself on a network interface. Why does this happen? Is there a way to disable this behavior?

**Comment by dmiller-nmap** [comment]
This is default behavior for Npcap, inherited from WinPcap because of some implementation details. The current way to avoid this is to use the `pcap_open()` function with the `PCAP_OPENFLAG_NOCAPTURE_LOCAL` flag. This unfortunately has additional side-effects that in some cases were relied upon by software built with WinPcap, so we have had to do some extra work to preserve behavior there. For new software, here are some recommendations:
1. Use packet filters to target only the desired packets (i.e. inbound based on address when possible). If this works, it will work the same on all platforms.
2. Use `pcap_setdirection()` as you would on a platform where it works, and ignore the error when it doesn't. We intend to support this in the future (#248), so this will avoid the need to change your application when that support is added.
3. Ensure your application can handle receiving packets that were injected this way. Aside from the implementation details alluded to above, it is likely we will continue to have this be the default behavior because that guarantees that a capture handle (`pcap_t`) will capture all matching traffic that transits the interface. We do hope to expose a better means of controlling this behavior, possibly using `pcap_setdirection()`.

I am closing this issue as a duplicate for #248, since that is where discussion of the new behavior should be done.

**Comment by Kollateral9** [comment]
This feature should be **really** implemented. Detailed explanation why here:

https://github.com/nmap/npcap/issues/248
