### ISSUE TITLE
Npcap version

### ISSUE THREAD

**Issue by SirimisettyRavi** [nmap/npcap#661]
Hi Team,

Is there any command to find out the Npcap version on windows. Please provide me.

**Comment by fyodor** [comment]
Thanks for your submission.  I'm closing thise since it's more of a question than an issue we have to track, but folks are welcome and encouraged to still leave a comment with their preferred ways to do this.  Other users might benefit as well.  If you're an Nmap OEM licensee with a support contract, please reach out through that channel.  You also might have good luck asking on a questions forum such as StackExchange.  Cheers.

**Comment by markpizz** [comment]
From my point of view, you can always look (using control panel or the Settings -> Apps & features) and the version is certainly visible there.

Also, if your leveraging the pcap API, then the pcap_lib_version() API will also provide the details...

**Comment by guyharris** [comment]
I shall presume that by "command" you meant a command that you can type on the cmd.exe command line.

If so, some Web searching found pages that indicated how to use PowerShell to get version information from a DLL, so, for Npcap, a command that will do the job is

    powershell -command "(Get-Item C:\Windows\System32\Packet.dll).VersionInfo.ProductVersion"

(successfully tested on my Windows 10 virtual machine).  This requires, of course, that you have PowerShell on your machine; earlier versions of might not have that by default.

> Also, if your leveraging the pcap API, then the pcap_lib_version() API will also provide the details...

That will, with Npcap, give you a string of the form

    Npcap version 1.71, based on libpcap version 1.10.2-PRE-GIT

**Comment by guyharris** [comment]
(Note that the PowerShell command, when run on `C:\Windows\System32\wpcap.dll`, will give you the *libpcap* version, not the *Npcap* version; that's why I ran it on Packet.dll rather than wpcap.dll.

Perhaps the *product* version for wpcap.dll should be the Npcap version and the *file* version should be 1.10.2-PRE-GIT or whatever the libpcap version is.

@fyodor @bonsaiviking: any thoughts on that?)
