### ISSUE TITLE
A Way to Protect the Usage of Npcap from a Malicious Program

### ISSUE THREAD

**Issue by spaceman5** [nmap/npcap#669]
Hi all

When you install Wireshark on a Windows 10 computer,
you will also have Npcap installed, as a Windows Driver,
in order to do the actual capturing of data, for Wireshark to process and display.

Now as long as you yourself run Wireshark, and use it,
then it's great that Npcap is installed on the computer, and running on it.

The problem is that after you finish using Wireshark (for that day),
Npcap remains installed, and remains enabled as a Driver.
This means that any other software can access it and use it, and very easily capture your data, since you yourself so nicely installed it and enabled it to work on your computer.

Now generally programs don't do that,
but a malicious one can use that to its advantage.

So my question:
Is there a way to have Npcap installed, yet Locked most of the time,
so eventho it's installed, no-one (or no program) can use it to capture data on that computer,
and then, only when you, the person who installed it (and locked it) want to use it,
you will temporarily unlock it (or enable it), which means it will now capture data and Wireshark will get it,
and then once done for that day, Lock it back.

Does such a feature exist?
Or if not, is there anything similar that can be used to achieve the same goal?

Thank you

**Comment by fyodor** [comment]
Hi @spaceman5.  During the Npcap installer (which pops up during WIreshark install), you can select the admin-only mode checkbox.  This prevents non-admin users from using the Npcap driver.  Of course that means you'd have to run Wireshark as admin.

**Comment by markpizz** [comment]
Imagine that your suggestion of a password were to be implemented.  If malicious software were to be on the system, it would implicitly be running with Admin credentials, and could change any magic password you might have set, or merely uninstalled Npcap with that setting and reinstalled npcap WITHOUT that magic password setting, and then do whatever it wants with the system.

If you are running everything as the administrator user then you have, by design, managed to have your system as unsecured.

**Comment by spaceman5** [comment]
Well,
it's indeed an important point to be aware of..

Thank you for this.
