### ISSUE TITLE
Error opening network interface: live packet capture not supported on this system

### ISSUE THREAD

**Issue by BAkdemirr** [nmap/npcap#683]
i've successfully installed libpcap 1.10.4 and npcap 1.74 on WINDOWS 10. npcap works with wireshark with no problem. libpcap working with no problem because i can run ndpi (works with offline pcap analyze but cant work in live capture mode). But npcap cant find any devices with the simpliest packet capture code that i wrote (below code)

![image](https://github.com/nmap/npcap/assets/64818115/0d281a6d-26dc-47a1-830e-7f7698ac8e9b)

i run the above code with admin privileges.
g++ -o main main.cpp -lpcap
./main.exe

it says: pcap_open_live() failed:  live packet capture not supported on this system
what should i do ? 

Npcap version: 1.74
libpcap version: 1.10.4
op system: win10

**Comment by guyharris** [comment]
By "successfully installed libpcap 1.10.4", do you mean that you built libpcap 1.10.4 from source code and installed the results of that build process?

If so, please note that:

- Npcap 1.75, at least, *includes* libpcap 1.10.4, so you don't need to build libpcap from source yourself if you just want libpcap 1.10.4;
- building libpcap from source on Windows requires that, among other things, you have the Npcap *SDK* installed - otherwise, it won't find Npcap's packet library, without which libpcap can't capture traffic on Windows, and it will build a "reading capture files supported, capturing live traffic not supported" version of libpcap.

Please see [the "building libpcap on Windows" README](https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.windows.md) if you're trying to build libpcap on and for Windows.

**Comment by BAkdemirr** [comment]
> By "successfully installed libpcap 1.10.4", do you mean that you built libpcap 1.10.4 from source code and installed the results of that build process?
> 
> If so, please note that:
> 
> * Npcap 1.75, at least, _includes_ libpcap 1.10.4, so you don't need to build libpcap from source yourself if you just want libpcap 1.10.4;
> * building libpcap from source on Windows requires that, among other things, you have the Npcap _SDK_ installed - otherwise, it won't find Npcap's packet library, without which libpcap can't capture traffic on Windows, and it will build a "reading capture files supported, capturing live traffic not supported" version of libpcap.
> 
> Please see [the "building libpcap on Windows" README](https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.windows.md) if you're trying to build libpcap on and for Windows.

Hi. I'm using msys2. i've installed libpcap simply writing pacman -S mingw-w64-x86_64-libpcap.
And i said successfully because the below code is working the output for the below code is: successfully reached the pcapng file
and also i can use ndpi offline packet capture with no problem (if i try to open live capture, it says Wi-Fi device not found)(the name Wi-Fi is true btw, i got the name from wireshark)
![image](https://github.com/nmap/npcap/assets/64818115/b9434c08-f0ba-47e8-b115-e532701b78cc)

So simply my problem with npcap is, it works with wireshark, it works with offline libpcap captures, but if i write the simpliest live capture code it does not work

**Comment by guyharris** [comment]
> I'm using msys2. i've installed libpcap simply writing pacman -S mingw-w64-x86_64-libpcap.

Perhaps *they* built it without capture support.  File an issue with them.

> So simply my problem with npcap is, it works with wireshark, it works with offline libpcap captures, but if i write the simpliest live capture code it does not work

Npcap works with Wireshark because Wireshark has already been compiled and loads up Npcap at run time (so that it will run on:

- systems without WinPcap or Npcap, although it won't capture traffic;
- systems with WinPcap;
- systems with Npcap).

However, if you try to *compile* a program with Npcap, you will have to install the Npcap SDK and build with that.  If you build a program with mingw-w64-x86_64-libpcap, that program will *NOT* use the libpcap from Npcap, it will use the libpcap from mingw-w64-x86_64-libpcap.  The libpcap from Npcap is built using the Npcap SDK, so it includes capture support; if the libpcap from mingw-w64-x86_64-libpcap was not build using the Npcap SDK, it will not include capture support and will not be able to capture traffic.

I strongly suggest you download the Npcap SDK from [the Npcap Web site](https://npcap.com), install it, arrange to build using that SDK - including linking with either:

- Lib/wpcap.lib, if you're building a 32-bit x86 application;
- Lib/x64/wpcap.lib, if you're building a 64-bit x86 (x86-64, AMD64, x64, whatever) application;
- Lib/ARM64/wpcap.lib, if you're building a 64-bit ARM application.

*Do not* link with any pcap.dll or libpcap.dll library, as those are not from Npcap and probably don't use the Npcap library and driver and thus won't support capturing packets.  (They'll support reading capture files, because that doesn't require a packet capture mechanism.)
