### ISSUE TITLE
Npcap error: PacketSendPacket failed: The offload operation on the network interface has been paused.  (2150891562)

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/npcap#699]
An Npcap OEM customer reported that network sends with Npcap were failing with the error "The offload operation on the network interface has been paused.  (2150891562)".

Npcap 1.70 and later change the way packet send operations report errors, so it is possible this condition existed before and was not detectable.

**Comment by fyodor** [comment]
Here is what we ended up reporting to the customer: "After further research, I am unable to find a specific cause for this error, but it is not generated by Npcap itself. It is an error from the underlying NDIS stack that Npcap is passing along to the caller of PacketSendPacket. In versions of Npcap prior to Npcap 1.70, including all versions of WinPcap, these errors were not reported, so software had no way of knowing if its packets were rejected and not sent. Depending on the nature of the error, you may find that you need to retransmit the packet or modify the packet so that it is not rejected by the stack. Npcap facilitates injection of the packets, but it cannot guarantee the transmission of the packets if the underlying stack rejects them."

**Comment by fyodor** [comment]
OK I'm closing this since it's not really actionable given our current understanding of the situation.  We're just reporting back that the system error that they weren't able to send the packet we gave to it for whatever reason.  The customer involved added a retransmission step for this case and we haven't heard back any problem with that approach.  If anyone wants to suggest any behavior change to Npcap related to this (like if you know of some way to mitigate whatever caused the underlying error or if you think Npcap should take some sort of action other than passing back the error), feel free to comment or open a new issue.  Cheers.
